/*
 *  uc-boot — sync CMP guard (loaded as uc.js). Loads uc-core.js async.
 *  Generated by scripts/build-uc-split.mjs — edit dev/gdpr.dev.js, then re-run.
 */
/*
 *  Cookie Consents Banner by Intastellar Solutions, International
 *  intastellarsolutions.com/gdpr-cookiebanner
 *  consents.cdn.intastellarsolutions.com/uc.js
 *  @copy 2022-2025 Intastellar Solutions, International
 *
*/
// --- Cross-site Consent Tracking ---
let allScripts = window.allScripts = [
    {
        /* Analytics Scripts which are beeing blocked */
        /* "([\-\.]clarity+)", */
        type: "statics",
        scripts: [
            "(mixpanel)",
            "([\-\.]googleoptimize+)",
            "([\-\.]piwik+)",
            "([\-\.]matomo+)",
            "([\-\.]bing+)",
            "([\-\.]slideshare+)",
            "([\-\.]siteimproveanalytics+)",
            "([\-\.]hotjar+)",
            "([\-\.]snapchat)",
            "([\-\.]contentsquare)",
            "([\-\.]6sc)",
            "([\-\.]nr-data)",
            "([\-\.]2o7)",
            "([\-\.]hackerone)",
            "([\-\.]gstatic)",
            "([\-\.]webtrends)",
            "([\-\.]webtrendslive)",
            "([\-\.]amplitude)",
            "([\-\.]adobe)",
            "([\-\.]mxpnl)",
            "([\-\.]mixpanel)",
            "([\-\.]gstatics+)",
            "([\-\.]adobedtm)",
            "([\-\.]adobedc)",
            "([\-\.]qualtrics+)",
            "([\-\.]pardot+)",
            "([\-\.]poultons+)",
            "([\-\.]chartbeat+)",
            "([\-\.]consensu+)",
            "([\-\.]clarity+)",
            "([\-\.]clarity-cdn+)",
            "([\-\.]vwo+)",
            "([\-\.]ip-only+)",
            "([\-\.]ggpht+)",
            "([\-\.]clearbitjs+)",
            "([\-\.]clearbitscripts+)",
            "([\-\.]optimizely+)",
            "([\-\.]segment+)",
            "([\-\.]quantserve+)[a-z]{2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    },
    {
        /* Marketing Scripts which are beeing blocked */
        /* 
            "([\-\.]googlesyndication+)",
            "([\-\.]googletagservices+)",
            "([\-\.]googleadservices+)",
            "([\-\.]omnisnippet+)",
        */
        type: "marketing",
        scripts: [
            "(_linkedin_partner_id|_linkedin_data_partner_ids|mailchimp|lntrk|twitter|instagram|trustpilot|chic_lite_data|openai|oaiq|bzrcdn\\.openai)",
            "([\-\.]twitter+)",
            "([\-\.]ads-twitter+)",
            "([\-\.]casalemedia+)",
            "(chimpstatic+)",
            "([\-\.]trustpilot+)",
            "([\-\.]mailchimp+)",
            "([\-\.]linkedin+)",
            "([\-\.]bing+)",
            "([\-\.]licdn+)",
            "([\-\.]amazon-adsystem+)",
            "([\-\.]adfrom+)",
            "([\-\.]demdex+)",
            "([\-\.]criteo+)",
            "([\-\.]clearbitjs+)",
            "([\-\.]clearbitscripts+)",
            "([\-\.]instagram+)",
            "([\-\.]stickyadstv+)",
            "([\-\.]mookie1+)",
            "([\-\.]doubleclick+)",
            "([\-\.]bidswitch+)",
            "([\-\.]jnqsge+)",
            "([\-\.]syuh+)",
            "([\-\.]youtube+)",
            "([\-\.]vimeo+)",
            "([\-\.]ninthdecimal+)",
            "([\-\.]casalemedia+)",
            "([\-\.]adsymptotic+)",
            "([\-\.]tremorhub+)",
            "([\-\.]agkn+)",
            "([\-\.]myvisualiq+)",
            "([\-\.]exelator+)",
            "([\-\.]openx+)",
            "([\-\.]adsrvr+)",
            "([\-\.]justpremium+)",
            "([\-\.]ants+)",
            "([\-\.]bluekai+)",
            "([\-\.]revcontent+)",
            "([\-\.]outbrain+)",
            "([\-\.]adscale+)",
            "([\-\.]pdst+)",
            "([\-\.]yahoo+)",
            "([\-\.]advertising+)",
            "([\-\.]adnxs+)",
            "([\-\.]scdn+)",
            "([\-\.]spotify+)",
            "([\-\.]facebook+)",
            "([\-\.]pinterest+)",
            "([\-\.]adform+)",
            "([\-\.]adnxs+)",
            "([\-\.]advertising+)",
            "([\-\.]adtech+)",
            "([\-\.]soundestlink+)",
            "([\-\.]soundest+)",
            "([\-\.]soundestvid+)",
            "([\-\.]soundestform+)",
            "([\-\.]tiktok+)",
            "([\-\.]taboola+)",
            "([\-\.]hubspot+)",
            "([\-\.]openai+)",
            /* "([\-\.]hs-sites+)", */
            "([a-z]+){2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    },
    {
        /* Functional Scripts which are beeing blocked */
        type: "functional",
        scripts: [
            "(maps.google.com+)",
            "(www.google.com/maps/+)",
            "([\-\.]googleapis+)",
            "([\-\.]gstatics+)",
            "([\-\.]cludo+)",
            "([\-\.]qbrick+)",
            "([\-\.]klarna+)",
            "([\-\.]paypal+)",
            "([\-\.]usersnap+)",
            "([\-\.]zoom+)",
            "([\-\.]cdnjs+)",
            "([\-\.]jsdelivr+)",
            "([\-\.]disqus+)([a-z]+){2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    }
];
let __intaCompiledScriptPatterns = null;
function intaGetCompiledScriptPatterns() {
    if (__intaCompiledScriptPatterns) {
        return __intaCompiledScriptPatterns;
    }
    __intaCompiledScriptPatterns = [];
    for (let i = 0; i < window.allScripts.length; i++) {
        let scriptType = window.allScripts[i].type;
        let patterns = window.allScripts[i].scripts;
        let regexes = [];
        for (let j = 0; j < patterns.length; j++) {
            try {
                regexes.push(new RegExp(patterns[j], "i"));
            } catch (eCompile) { /* ignore invalid regex */ }
        }
        __intaCompiledScriptPatterns.push({ type: scriptType, regexes: regexes });
    }
    return __intaCompiledScriptPatterns;
}
window["optimizely"] = window["optimizely"] || [];
window["optimizely"].push({
    "type": "optOut",
    "isOptOut": true
});

window.pintrk = window.pintrk || function () {
    window.pintrk.queue.push(Array.prototype.slice.call(arguments));
};
window.pintrk.queue = window.pintrk.queue || [];

pintrk('setconsent', false);

window.VWO = window.VWO || [];
window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
window.VWO.init(2); // default to pending
window.INTA = window.INTA || {};
window.INTA.observedCookieSource = 'unknown';
// --- VWO Cookie Consent Integration (latest, per docs) ---
function updateVwoConsent(consents) {
    // VWO expects: 1 = accepted, 2 = pending, 3 = rejected
    // VWO runs when marketing OR statistical (analytics) cookies are accepted — not only marketing.
    var state = 2;
    if (!consents) {
        window.VWO = window.VWO || [];
        window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
        window.VWO.init(state);
        return;
    }
    function granted(v) {
        return v === true || v === "checked";
    }
    function denied(v) {
        return v === false || v === "unchecked";
    }
    var marketingOn = granted(consents.advertisementCookies) || consents.marketing === true;
    var statsOn = granted(consents.staticsticCookies) || consents.analytics === true;
    var marketingOff = denied(consents.advertisementCookies) || consents.marketing === false;
    var statsOff = denied(consents.staticsticCookies) || consents.analytics === false;

    if (marketingOn || statsOn) {
        state = 1;
    } else if (marketingOff && statsOff) {
        state = 3;
    } else {
        state = 2;
    }
    window.VWO = window.VWO || [];
    window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
    window.VWO.init(state);
    if (typeof window.VWO.onVariationApplied === 'function') {
        window.location.reload();
    }
}
// --- End VWO Cookie Consent Integration ---

/**
 * True when we should run WP Consent API integration (`wp_set_consent`, dataLayer mirror, cookie sync).
 * Requires `wp_set_consent` from WordPress. Set `INTA.settings.wpConsentApi = false` (before or early after
 * the script) when Google Advanced Consent Mode must be authoritative via `gtag`/GTM only — bridges such as
 * Site Kit that map WP cookies → Consent Mode can otherwise fight Intastellar’s updates.
 * @see https://wpconsentapi.org
 */
// --- Helper function to detect Vendors of Cookies (lazy-loaded; stub until uc-vendors loads) ---
function detectCookieVendor(cookie) {
    if (typeof window.__intaDetectCookieVendor === 'function') {
        return window.__intaDetectCookieVendor(cookie);
    }
    return 'unknown vendor';
}

// --- Helper: Map cookie name to consent type (populated when uc-vendors loads) ---
var COOKIE_CONSENT_TYPE_MAP = null;

// Load uc-vendors.js on DOMContentLoaded to reduce initial parse/execute (detectCookieVendor + map ~15KB)
function loadUcVendors() {
    if (window.__intaDetectCookieVendor) return;
    var base = (typeof window.INTA !== 'undefined' && window.INTA.settings && window.INTA.settings.vendorsUrl) || 'https://consents.cdn.intastellarsolutions.com/uc-vendors.js';
    var s = document.createElement('script');
    s.src = base;
    s.async = true;
    intaAppendToDocumentHead(s);
    s.onload = function () {
        COOKIE_CONSENT_TYPE_MAP = window.__intaCookieConsentTypeMap || null;
    };
}

function getConsentTypeForCookie(cookieName) {
    // Delegate to uc-vendors when loaded
    if (typeof window.__intaGetConsentTypeForCookie === 'function') {
        return window.__intaGetConsentTypeForCookie(cookieName);
    }
    // Fallback until uc-vendors loads
    if (COOKIE_CONSENT_TYPE_MAP && COOKIE_CONSENT_TYPE_MAP[cookieName]) return COOKIE_CONSENT_TYPE_MAP[cookieName];
    if (COOKIE_CONSENT_TYPE_MAP) {
        for (let key in COOKIE_CONSENT_TYPE_MAP) {
            if (cookieName.startsWith(key)) return COOKIE_CONSENT_TYPE_MAP[key];
        }
    }
    return 'marketing';
}

// --- Blocked iframe / embed consent copy (lazy-loaded uc-blocked-iframe.js) ---
var __intaBlockedIframeLoadStarted = false;

function loadUcBlockedIframeMessages() {
    if (window.__intaBlockedIframeContentMessage) {
        return;
    }
    if (__intaBlockedIframeLoadStarted) {
        return;
    }
    __intaBlockedIframeLoadStarted = true;
    var base = (typeof window.INTA !== "undefined" && window.INTA.settings && window.INTA.settings.blockedIframeUrl)
        || "https://consents.cdn.intastellarsolutions.com/uc-blocked-iframe.js";
    if (typeof intastellarDevMode !== "undefined" && intastellarDevMode) {
        base = "../../dev/uc-blocked-iframe.dev.js";
    }
    var s = document.createElement("script");
    s.src = base;
    s.async = true;
    intaAppendToDocumentHead(s);
}

function intaEnsureBlockedIframeMessagesLoaded() {
    loadUcBlockedIframeMessages();
}

function intaResolveBlockedIframeLocaleKey() {
    if (typeof window.__intaResolveBlockedIframeLocaleKey === "function") {
        return window.__intaResolveBlockedIframeLocaleKey();
    }
    return "english";
}

function intaBlockedIframeContentMessage(domain, localeKey) {
    if (typeof window.__intaBlockedIframeContentMessage === "function") {
        return window.__intaBlockedIframeContentMessage(domain, localeKey);
    }
    return "<p>This content is provided by " + domain + ".</p>";
}

function intaBlockedIframeButtonText(scriptType, localeKey) {
    if (typeof window.__intaBlockedIframeButtonText === "function") {
        return window.__intaBlockedIframeButtonText(scriptType, localeKey);
    }
    return "Accept cookies";
}

function intaNormalizeBlockedIframeDomain(domain, node, cookieList) {
    if (node && node.classList && node.classList.contains("trustpilot-widget")) {
        domain = "www.trustpilot.com";
    }
    var list = cookieList || (typeof inta_marketingCookieList !== "undefined" ? inta_marketingCookieList : []);
    list.forEach(function (cookie) {
        var i = 0, d = domain, p = d.split(".");
        d = p.slice(-1 - ++i).join(".");
        domain = d;
        if (cookie && cookie.domains && cookie.domains.indexOf(domain) > -1) {
            domain = cookie.vendor;
        }
    });
    return domain;
}

function intaPickBlockedIframeStrings(domain, node, scriptType, cookieList) {
    intaEnsureBlockedIframeMessagesLoaded();
    var localeKey = intaResolveBlockedIframeLocaleKey();
    var normalized = intaNormalizeBlockedIframeDomain(domain, node, cookieList);
    return {
        textLanguage: intaBlockedIframeContentMessage(normalized, localeKey),
        btnText: intaBlockedIframeButtonText(scriptType, localeKey)
    };
}
// --- Start Cookie Interception ---
(function () {
    let desc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie');
    Object.defineProperty(document, 'cookie', {
        configurable: true,
        enumerable: true,
        get: function () {
            return desc.get.call(this);
        },
        set: function (cookieString) {
            window.INTA.observedCookieSource = 'cookie';
            try {
                let cookieName = cookieString.split('=')[0].trim();
                let rawValue = cookieString.split('=')[1]?.split(';')[0];
                let cookieDomain = cookieString.split(';').find(part => part.trim().toLowerCase().startsWith('domain='))?.split('=')[1]?.trim() || window.location.hostname;
                // Use cookie name to determine consent type
                let consentType = getConsentTypeForCookie(cookieName);
                recordCookie({
                    name: cookieName,
                    source: window.INTA.observedCookieSource || 'unknown',
                    observedAt: Date.now(),
                    path: window.location.pathname,
                    domain: window.location.hostname,
                    cookieDomain,
                    rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
                    hadValuePreConsent: typeof rawValue === 'string' && rawValue.length > 0,
                    consentGiven: hasConsent(consentType),
                    vendor: detectCookieVendor({ name: cookieName, value: rawValue })
                })
            } catch (e) { /* ignore */ }
            return desc.set.call(this, cookieString);
        }
    });
})();

// --- CookieStorage Observer ---
if ("cookieStore" in window) {
    cookieStore.addEventListener("change", (event) => {
        event.changed.forEach(cookie => {
            window.INTA.observedCookieSource = 'cookieStore';
            let consentType = getConsentTypeForCookie(cookie.name);
            recordCookie({
                name: cookie.name,
                source: 'cookieStore',
                observedAt: Date.now(),
                path: cookie.path || window.location.pathname,
                domain: cookie.domain || window.location.hostname,
                cookieDomain: cookie.domain || window.location.hostname,
                rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
                hadValuePreConsent: 0,
                consentGiven: hasConsent(consentType),
                vendor: detectCookieVendor({ name: cookie.name, value: cookie.value })
            })
        })
    });
}

// --- Start localStorage Interception ---
(function () {
    let originalSetItem = localStorage.setItem;
    localStorage.setItem = function (key, value) {
        window.INTA.observedCookieSource = 'localStorage';
        let consentType = getConsentTypeForCookie(key);
        recordCookie({
            name: key,
            source: 'localStorage',
            observedAt: Date.now(),
            path: window.location.pathname,
            domain: window.location.hostname,
            rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
            hadValuePreConsent: typeof value === 'string' && value.length > 0,
            consentGiven: hasConsent(consentType),
            vendor: detectCookieVendor({ name: key, value: value })
        });
        return originalSetItem.apply(this, arguments);
    };
})();

// --- Start memory Interception (example) ---
window.INTA.memorySet = function (key, value) {
    window.INTA.observedCookieSource = 'memory';
    let consentType = getConsentTypeForCookie(key);
    recordCookie({
        name: key,
        value: value,
        source: 'memory',
        observedAt: Date.now(),
        path: window.location.pathname,
        domain: window.location.hostname,
        rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
        hadValuePreConsent: typeof value === 'string' && value.length > 0,
        consentGiven: hasConsent(consentType),
        vendor: detectCookieVendor({ name: key, value: value })
    });
    window.INTA._memory = window.INTA._memory || {};
    window.INTA._memory[key] = value;
};

function IntastellarSnapShot(stage) {

}

// Example usage:
// let rootDomain = "group1.com";
// let partnerDomains = ["domain-a.com", "domain-b.com"];
// requestConsentState('user-123', rootDomain, partnerDomains);
// setConsentState('user-123', { marketing: true, statistics: false, functional: true }, rootDomain, partnerDomains);
// --- End Cross-site Consent Tracking ---
let intaCookiePref = "IntastellarConsentSolution";
let int_hideCookieBannerName = window.int_hideCookieBannerName = intaCookiePref;
let int_FunctionalCookies = intaCookiePref + ":Functional-cookies";
let int_marketingCookies = intaCookiePref + ":Advertisment-cookies";
let int_staticsticCookies = intaCookiePref + ":Statistics-cookies";
let int_visitorCheck = intaCookiePref + "visitorCheck";
let button__acceptAll = document.querySelector(".intastellarCookieBanner__acceptAll");
let button__acceptAllNecessary = document.querySelector(".intastellarCookieBanner__acceptNecessary");
let intastellarShowHideDetailsText = "Show details";
let adsbygoogle = window.adsbygoogle || [];
let intastellarCookieBannerRootDomain = "https://consents.cdn.intastellarsolutions.com";
let intastellarAssetsCDNdomain = "https://www.intastellar-consents.com";
let intaCookieConsents = window.intaCookieConsents = (getCookie(int_hideCookieBannerName)) ? JSON.parse(decodeIntaConsentsObject(getCookie(int_hideCookieBannerName)?.split(".")[2]))?.consents : null;
window.uetq = window.uetq || [];
// On page load, update VWO consent if consent object exists
if (intaCookieConsents) {
    updateVwoConsent(intaCookieConsents);
}
let intaCookieConsentsUserId = (getCookie(int_hideCookieBannerName)) ? JSON.parse(decodeIntaConsentsObject(getCookie(int_hideCookieBannerName)?.split(".")[2]))?.uid : null;

/** Intastellar script URL when `document.currentScript` is null (Remix, Vite, Webpack, ES modules). */
function intaGuessIntastellarScriptSrc() {
    try {
        if (document.currentScript && document.currentScript.src) {
            return document.currentScript.src;
        }
    } catch (e) {
        /* ignore */
    }
    const scripts = document.getElementsByTagName("script");
    for (let i = scripts.length - 1; i >= 0; i--) {
        const s = scripts[i];
        const src = s && s.src;
        if (!src) {
            continue;
        }
        if (/uc\.js|\/uc\.js|consents\.cdn|intastellar-consents|gdpr\.dev|\/cb\.js|\/cb\.dev|floating\.js/i.test(src)) {
            return src;
        }
    }
    return "";
}

function findScriptParameter(value) {
    const currentURL = intaGuessIntastellarScriptSrc();
    if (!currentURL || currentURL.indexOf(value) === -1) {
        return undefined;
    }
    try {
        const url = new URL(currentURL, window.location.href);
        return url.searchParams.get(value);
    } catch (e) {
        return undefined;
    }
}

let isGtmMode = findScriptParameter("ref") === "gtm";
let isWordPress = document.getElementById('intastellar-gdpr-settings-js') !== null;
let FunctionalCheckbox = document.querySelector("#functional");
let StaticsCheckBox = document.querySelector("#statics");
let MarketingCheckBox = document.querySelector("#marketing");
let pluginSource = findScriptParameter("utm_source") === undefined ? "Intastellar+Solutions+Cookiebanner" : findScriptParameter("utm_source");
window.platform = findScriptParameter("utm_source") === undefined ? "Manual" : findScriptParameter("utm_source");
let poweredBy = "";
window.dataLayer = window.dataLayer || [];
intaWpInstallDataLayerConsentMirror();
let intaConsentsObjectVariable = {
    consents: {
        staticsticCookies: false,
        functionalCookies: false,
        advertisementCookies: false,
    },
    time: new Date().toGMTString(),
    uid: Math.random().toString(16).slice(2),
    domain: window?.INTA?.settings?.rootDomain || window.location.host,
    sharingDomains: [],
    tcString: null,
}

window._paq = window._paq || [];
_paq.push(['requireConsent']);


window.clarity && window.clarity('consentv2', {
    ad_Storage: "denied",
    analytics_Storage: "denied"
});

window.uetq.push('consent', 'default', {
    'ad_storage': 'denied'
});



window.disableHubSpotCookieBanner = true;
var _hsp = (window._hsp = window._hsp || []);

function gtag() {
    dataLayer.push(arguments);
}


if (window._intaConsentInitialized) {
    console.log('Intastellar consent already initialized, skipping...');
}

window._intaConsentInitialized = true;

intaWpEnsureConsentTypeOptinAnnouncedOnce();

if (!isGtmMode && !window._gtagDefaultFired && typeof gtag === 'function') {
    // Only set defaults if GTM hasn't already done so
    if (!window.google_tag_manager || !window.google_tag_manager['consent_default_set']) {
        // Strict opt-in regions (GDPR-style). ISO 3166: 'CA' = Canada, not California.
        // California is handled separately below via region ['US-CA'] (CCPA / opt-out style).
        gtag('consent', 'default', {
            "ad_storage": 'denied',
            "personalization_storage": 'denied',
            "analytics_storage": 'denied',
            "functionality_storage": 'denied',
            "ads_data_redaction": 'granted',
            "ad_user_data": 'denied',
            "ad_personalization": 'denied',
            "security_storage": 'granted',
            "url_passthrough": true,
            "wait_for_update": 500,
            "region": ['EU', 'UK', 'CH', 'NO', 'IS', 'LI', 'CA', 'BR', 'ZA', 'TR', 'AR', 'IL', 'TH']
        });
        /* console.log("Intastellar Consents: Applied STRICT defaults (EU/UK/CA/BR/etc.)"); */

        // California only: CCPA-style defaults (region US-CA). Rest of US uses global baseline below.
        gtag('consent', 'default', {
            "ad_storage": 'granted',
            "personalization_storage": 'granted',
            "analytics_storage": 'granted',
            "functionality_storage": 'granted',
            "ads_data_redaction": 'denied',
            "ad_user_data": 'granted',
            "ad_personalization": 'granted',
            "security_storage": 'granted',
            "url_passthrough": true,
            "wait_for_update": 500,
            "region": ['US-CA']
        });
        /* console.log("Intastellar Consents: Applied CALIFORNIA defaults (US-CA)"); */

        // Global baseline: strict (denied) for every region not matched above.
        // Regional rows above take precedence (strict list + TH, etc., and US-CA opt-out style).
        // No separate "rest of world granted" row — that would opt non-listed countries in by default.
        gtag('consent', 'default', {
            'ad_storage': 'denied',
            'personalization_storage': 'denied',
            'analytics_storage': 'denied',
            'functionality_storage': 'denied',
            'ads_data_redaction': 'denied',
            'ad_user_data': 'denied',
            'ad_personalization': 'denied',
            'security_storage': 'granted',
            'url_passthrough': true,
            'wait_for_update': 500,
        });
        window._gtagDefaultFired = true;
    }
} else if (isGtmMode) { }

if (typeof fbq === "undefined" || typeof fbq === "null") {
    function fbq() { }
}

if (hasConsent("advertisement")) {
    gtag('consent', 'update', {
        'personalization_storage': 'granted',
        'ads_data_redaction': 'granted',
        'ad_storage': 'granted',
        'ad_user_data': 'granted',
        'ad_personalization': 'granted',
        'url_passthrough': true,
    });

    // Pintrk
    if (typeof pintrk === 'function') {
        try {
            pintrk('setconsent', true);
        } catch (e) { /* ignore */ }
    }

    window.uetq.push('consent', 'update', {
        'ad_storage': 'granted'
    });

    window.clarity && window.clarity('consentv2', {
        ad_Storage: "granted",
        analytics_Storage: "denied"
    });

    fbq('consent', 'grant');
    // Enable ads
    (adsbygoogle = window.adsbygoogle || []).pauseAdRequests = 0;
    (adsbygoogle = window.adsbygoogle || []).requestNonPersonalizedAds = 0;

}

if (hasConsent("analytics")) {
    gtag('consent', 'update', {
        'analytics_storage': 'granted',
        'url_passthrough': true,
    })
    window.clarity && window.clarity('consentv2', {
        ad_Storage: "denied",
        analytics_Storage: "granted"
    });
    window.uetq.push('consent', 'update', {
        'analytics_storage': 'granted'
    });
    
    _paq.push(['setConsentGiven']);
}

if (hasConsent("functional")) {
    gtag('consent', 'update', {
        'functionality_storage': 'granted',
    })
    window.uetq.push('consent', 'update', {
        'functionality_storage': 'granted'
    });

}

// --- Server-Side Tagging & Interception Implementation ---
// Helper: Determine consent type for a given URL using allScripts regex
function getConsentTypeForUrl(url) {
    if (!url) return 'marketing';
    let compiled = intaGetCompiledScriptPatterns();
    for (let i = 0; i < compiled.length; i++) {
        let scriptType = compiled[i].type;
        let regexes = compiled[i].regexes;
        for (let j = 0; j < regexes.length; j++) {
            try {
                if (regexes[j].test(url)) {
                    if (scriptType === 'statics') return 'statistics';
                    return scriptType;
                }
            } catch (e) { /* ignore */ }
        }
    }
    // Default fallback
    return 'marketing';
}

/**
 * Machine-readable IAB device-storage disclosures and GVL-listed vendor URLs.
 * cb.js sets `intaIsGvlVendorPassThroughUrl` / `__intaGvlPassThroughUrls` after vendors load; this also matches
 * common disclosure JSON paths so XHR is not blocked before the GVL finishes loading.
 */
function intaIsGvlPassThroughRequest(url) {
    if (!url || typeof url !== "string") {
        return false;
    }
    if (typeof window.intaIsGvlVendorPassThroughUrl === "function") {
        try {
            if (window.intaIsGvlVendorPassThroughUrl(url)) {
                return true;
            }
        } catch (eFn) { /* ignore */ }
    }
    let u = url.trim();
    let list = window.__intaGvlPassThroughUrls;
    if (Array.isArray(list) && list.indexOf(u) !== -1) {
        return true;
    }
    try {
        let parsed = new URL(u, window.location.origin);
        let hosts = window.__intaGvlPassThroughHosts;
        if (Array.isArray(hosts) && hosts.indexOf(parsed.hostname) !== -1) {
            return true;
        }
        let p = (parsed.pathname || "").toLowerCase();
        if (parsed.protocol === "https:" && p.endsWith(".json") && /devicestorage|device_storage|compliance_devicestorage/.test(p)) {
            return true;
        }
    } catch (e0) { /* ignore */ }
    return false;
}

// Helper: Send intercepted data to backend for storage/categorization

// Consent check helper
function hasConsent(type) {
    // type: 'functional', 'statistics', 'marketing'
    if (!window.intaCookieConsents) return false;
    if (type === 'functional') return window.intaCookieConsents.functionalCookies === 'checked';
    if (type === 'statistics' || type === 'analytics') return window.intaCookieConsents.staticsticCookies === 'checked';
    if (type === 'advertisement' || type === 'marketing') return window.intaCookieConsents.advertisementCookies === 'checked';
    return false;
}

let ALLOWLIST = [
    location.origin,
    "https://intastellar.app",
    "https://www.intastellarsolutions.com",
    "https://analytics.intastellarsolutions.com",
    "https://api.intastellarsolutions.com",
    "https://apis.intastellarsolutions.com",
    "https://apis.intastellaraccounts.com",
    "https://consents.intastellarsolutions.com",
    "https://vendor-list.consensu.org",
    "/dev/gvl-local.json",
    "https://forms.hsforms.com",
    "https://js.hs-scripts.com",
    "https://js.hsforms.net",
    "https://api.hsforms.com",
    "https://forms.hubspot.com",
    "https://track.hubspot.com",
    "https://js.usemessages.com",
    "https://cdn2.hubspot.net",
    "https://cdn.hsforms.net",
    "https://cdn.weglot.com",
    "https://dev.visualwebsiteoptimizer.com",
    "https://www.google-analytics.com",
    "https://region1.google-analytics.com"
];

function intaNormalizeHostname(host) {
    if (!host) {
        return "";
    }
    return String(host).split(":")[0].replace(/^www\./i, "").toLowerCase();
}

/** Best-effort registrable domain when `INTA.settings.rootDomain` is not set (e.g. `booking.example.com` → `example.com`). */
function intaDeriveSiteRootFromHostname(hostname) {
    let h = intaNormalizeHostname(hostname);
    if (!h) {
        return "";
    }
    let parts = h.split(".");
    if (parts.length <= 2) {
        return h;
    }
    return parts.slice(-2).join(".");
}

function intaGetSiteRootCandidates(pageHostname) {
    let roots = [];
    let configured = window.INTA && window.INTA.settings && window.INTA.settings.rootDomain;
    if (configured) {
        roots.push(intaNormalizeHostname(String(configured)));
    }
    let derived = intaDeriveSiteRootFromHostname(pageHostname);
    if (derived) {
        roots.push(derived);
    }
    let partners = window.INTA && window.INTA.settings && window.INTA.settings.partnerDomain;
    if (Array.isArray(partners)) {
        partners.forEach(function (d) {
            if (d) {
                roots.push(intaNormalizeHostname(String(d)));
            }
        });
    }
    return roots.filter(function (r, i, arr) {
        return r && arr.indexOf(r) === i;
    });
}

function intaIsHostUnderSiteRoot(host, root) {
    let h = intaNormalizeHostname(host);
    let r = intaNormalizeHostname(root);
    if (!h || !r) {
        return false;
    }
    return h === r || h.endsWith("." + r);
}

/** True when target and page share the same configured/derived root (root ↔ subdomain in either direction). */
function intaIsSameSiteHost(targetHostname, pageHostname) {
    let t = intaNormalizeHostname(targetHostname);
    let p = intaNormalizeHostname(pageHostname);
    if (!t || !p) {
        return false;
    }
    if (t === p) {
        return true;
    }
    let roots = intaGetSiteRootCandidates(p);
    for (let i = 0; i < roots.length; i++) {
        if (intaIsHostUnderSiteRoot(t, roots[i]) && intaIsHostUnderSiteRoot(p, roots[i])) {
            return true;
        }
    }
    return false;
}

function isAllowed(url) {
    try {
        let parsedUrl = new URL(url, window.location.origin);
        // Allow all requests to the same origin
        if (parsedUrl.origin === window.location.origin) return true;

        if (
            /(?:\.hubspot\.com|\.hsforms\.com|\.hs-scripts\.com|\.hsforms\.net|\.usemessages\.com|\.cdn2\.hubspot\.net|\.cdn\.hsforms\.net)$/i.test(parsedUrl.hostname)
        ) {
            return true;
        }

        // Allow if matches any allowlist origin
        if (ALLOWLIST.some(domain => parsedUrl.origin === domain)) return true;

        // Root domain ↔ subdomain (either direction), e.g. booking.asasoftware.aero → asasoftware.aero/collect
        if (intaIsSameSiteHost(parsedUrl.hostname, window.location.hostname)) {
            return true;
        }

        // Optionally allow other trusted domains here
        return false;
    } catch (e) {
        return false;
    }
}


// Intercept fetch with consent check
let originalFetch = window.fetch;
window.fetch = function (resource, config) {
    let url = (typeof resource === 'string') ? resource : resource.url;
    // Prevent recursion for backend endpoint
    if (isAllowed(url)) {
        return originalFetch.apply(this, arguments);
    }
    if (intaIsGvlPassThroughRequest(url)) {
        return originalFetch.apply(this, arguments);
    }
    let isExternal = !url.startsWith(window.location.origin);
    if (isExternal) {
        let consentType = getConsentTypeForUrl(url);
        if (!hasConsent(consentType)) {
            if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                console.log('[GDPR] Blocked fetch:', url, 'type:', consentType);
            }
            // Silently block: return a resolved Promise with undefined
            return Promise.resolve(undefined);
        }
    }
    return originalFetch.apply(this, arguments);
};

// Intercept XMLHttpRequest with consent check
let OriginalXHR = window.XMLHttpRequest;
function CustomXHR() {
    let xhr = new OriginalXHR();
    let open = xhr.open;
    xhr.open = function (method, url, ...args) {
        if (isAllowed(url)) {
            return open.apply(this, arguments);
        }
        if (intaIsGvlPassThroughRequest(url)) {
            return open.apply(this, arguments);
        }
        let isExternal = !url.startsWith(window.location.origin);
        if (isExternal) {
            let consentType = getConsentTypeForUrl(url);
            if (!hasConsent(consentType)) {
                if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                    console.log('[GDPR] Blocked XHR:', url, 'type:', consentType);
                }
                // Silently block: do not send request
                return; // open not called, so request never sent
            }
        }
        return open.apply(this, arguments);
    };
    return xhr;
}
window.XMLHttpRequest = CustomXHR;
// Intercept navigator.sendBeacon with consent check
let originalSendBeacon = navigator.sendBeacon;
navigator.sendBeacon = function (url, data) {
    // Prevent recursion for backend endpoint
    if (isAllowed(url)) {
        return originalSendBeacon.apply(this, arguments);
    }
    if (intaIsGvlPassThroughRequest(url)) {
        return originalSendBeacon.apply(this, arguments);
    }
    let isExternal = !url.startsWith(window.location.origin);
    if (isExternal) {
        let consentType = getConsentTypeForUrl(url);
        if (!hasConsent(consentType)) {
            if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                console.log('[GDPR] Blocked beacon:', url, 'type:', consentType);
            }
            // Silently block: do not send beacon
            return false;
        }
        sendToBackend({
            type: 'beacon',
            url,
            data: typeof data === 'string' ? data : '[binary]',
            consentType,
            timestamp: Date.now()
        });
    }
    return originalSendBeacon.apply(this, arguments);
};
// --- End Server-Side Tagging & Interception Implementtion ---


if (!hasConsent("advertisement")) {
    fbq('consent', 'revoke');
}

let settingsMessage = "";
let foundScripts = window.foundScripts = [];
let intCookieIcon = intastellarAssetsCDNdomain + "/assets/icons/cookie_settings.svg";
window.dataLayer = window.dataLayer || [];
(adsbygoogle = window.adsbygoogle || []).pauseAdRequests = 1;
(adsbygoogle = window.adsbygoogle || []).requestNonPersonalizedAds = 1;

/* - - - Setup - - - */
if (window.INTA === undefined) {
    window.INTA = {
        policy_link: undefined,
        settings: {
            company: undefined,
            lang: "auto",
            color: "#c09f53",
            keepInLocalStorage: ["firstLoad", int_FunctionalCookies, int_hideCookieBannerName, int_marketingCookies, int_staticsticCookies],
            arrange: "ltr",
            logo: intCookieIcon,
            partnerDomain: null,
            StyleSheet: null,
            design: "overlay",
        }
    }
}

function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(";");
    for (var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) === " ") {
            c = c.substring(1);
        }

        /* console.log(localStorage.getItem(cname), cname); */

        if (c.indexOf(name) === 0 && localStorage.getItem(cname) === null) {
            return c.substring(name.length, c.length);
        } else if (localStorage.getItem(cname) !== null) {
            return localStorage.getItem(cname);
        }
    }
    return "";
}

function randomIntFromInterval(min, max) { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min)
}

/**
 * CCPA / CPRA: persist `salesOfDataAllowed` only for visitors in California (no extra banner checkbox).
 * Region: `window._intaGeo` from ipapi (see fetch above), or override `INTA.settings.ccpa.inUsCalifornia` (boolean),
 * or both `INTA.settings.ccpa.country === "US"` and `INTA.settings.ccpa.regionCode === "CA"` (e.g. server-injected).
 * Value: false if `localStorage.ccpa_opt_out` ("Do not sell" flow); else mirrors marketing consent (`advertisementCookies === "checked"`).
 * When region is still unknown, the field is left unchanged (not added, not removed) until geo or override is available.
 */
function intaCaliforniaRegionState() {
    try {
        var ccpa = window.INTA && window.INTA.settings && window.INTA.settings.ccpa;
        if (ccpa && typeof ccpa.inUsCalifornia === "boolean") {
            return ccpa.inUsCalifornia ? "yes" : "no";
        }
        if (ccpa && ccpa.country && ccpa.regionCode) {
            return (ccpa.country === "US" && ccpa.regionCode === "CA") ? "yes" : "no";
        }
        var g = window._intaGeo;
        if (g && g.country && g.region_code) {
            return (g.country === "US" && g.region_code === "CA") ? "yes" : "no";
        }
    } catch (e) { /* ignore */ }
    return "unknown";
}

function intaMarketingConsentImpliesSaleAllowed(consents) {
    if (!consents || typeof consents !== "object") return false;
    return consents.advertisementCookies === "checked" || consents.advertisementCookies === true;
}

function intaSyncSalesOfDataAllowedOnConsents(consents) {
    if (!consents || typeof consents !== "object") return;
    var region = intaCaliforniaRegionState();
    if (region === "no") {
        delete consents.salesOfDataAllowed;
        return;
    }
    if (region === "unknown") {
        return;
    }
    try {
        if (typeof localStorage !== "undefined" && localStorage.getItem("ccpa_opt_out") === "true") {
            consents.salesOfDataAllowed = false;
            return;
        }
    } catch (e) { /* ignore */ }
    consents.salesOfDataAllowed = intaMarketingConsentImpliesSaleAllowed(consents);
}

function encodeIntaConsentsObject(string, base) {
    try {
        var parsed = JSON.parse(string);
        if (parsed && typeof parsed === "object" && parsed.consents && typeof parsed.consents === "object") {
            intaSyncSalesOfDataAllowedOnConsents(parsed.consents);
            string = JSON.stringify(parsed);
        }
    } catch (e) {
        /* not a full consent JSON payload — encode as-is */
    }
    var number = "0";
    var length = string.length;
    for (var i = 0; i < length; i++)
        number += string.charCodeAt(i).toString(base);
    return base + "." + number;
}

function decodeIntaConsentsObject(number) {
    var string = "";
    number = number?.slice(1);
    var length = number?.length;
    for (var i = 0; i < length;) {
        var code = number?.slice(i, i += 2);
        string += String.fromCharCode(parseInt(code, parseInt(getCookie(int_hideCookieBannerName)?.split(".")[1])));
    }

    return string;
}

let intastellarDevMode = (function () {
    var hostname = window.location.hostname;
    return hostname === "localhost"
        || hostname.indexOf("127.0.0.1") > -1 && window.INTA.dev === true
        || hostname.indexOf("0.0.0.0") > -1 && window.INTA.dev === true
        || hostname.indexOf("192.168.") > -1 && window.INTA.dev === true
        || hostname.indexOf("::1") > -1 && window.INTA.dev === true
        ? true : false;
})();

let tmpl = document.createElement('template');
tmpl.innerHTML = `
<style>:host { display:block; width: auto; max-width: 560px; }</style> <!-- look ma, scoped styles -->
<slot></slot>
`;

/* - - - Function to get Cookie Settings from url and set the cookie - - - */
function intaSetCookieSettings() {
    let urlParams = new URLSearchParams(window.location.search);
    let cookieSettings = urlParams.get('intaCookieSettings');
    let reload = urlParams.get('reload');

    /*  console.log("Cookie Settings from URL", window.location.host); */
    if (cookieSettings && !reload) {
        /* console.log("Setting the new cookie" + cookieSettings); */

        document.cookie = int_hideCookieBannerName + "=" + cookieSettings + "; expires=" + cookieLifeTime +
            "; path=/; " +
            intCookieDomain +
            "SameSite=Lax";
        // Reload the page and append to exising query string the reload parameter
        window.location.href = window.location.href + "&reload=true";
    }
};

function intaAppendToDocumentHead(node) {
    if (!node) {
        return;
    }
    const head = document.head
        || document.querySelector("head")
        || document.getElementsByTagName("head")[0];
    try {
        if (head) {
            head.appendChild(node);
            return;
        }
    } catch (e) {
        /* ignore */
    }
    try {
        const fallback = document.body || document.documentElement;
        if (fallback) {
            fallback.appendChild(node);
        }
    } catch (e2) {
        /* ignore */
    }
}
let notRequired;
let m;
/* Helper function to merge arrays */
let merge = (first, second, third) => {
    /* first.splice(1, 0, "^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+"); */
    for (let i = 0; i < second.length; i++) {
        first.push(second[i]);
    }
    if (third !== undefined) {
        for (let i = 0; i < third.length; i++) {
            first.push(third[i])
        }
    }
    return first;
}
/* autoads-preview.googleusercontent.com */
/* Getting user prefrence settings from Local storage: checked means user has allowed. False means cookies needs to be blocked */
if (intaCookieConsents?.functionalCookies === "checked" &&
    intaCookieConsents?.staticsticCookies !== "checked" &&
    intaCookieConsents?.advertisementCookies !== "checked") {
    m = merge(allScripts[1].scripts, allScripts[0].scripts);
} else if (intaCookieConsents?.advertisementCookies === "checked" &&
    intaCookieConsents?.staticsticCookies !== "checked" &&
    intaCookieConsents?.functionalCookies !== "checked") {
    m = merge(allScripts[2].scripts, allScripts[0].scripts);
} else if (intaCookieConsents?.staticsticCookies === "checked" &&
    intaCookieConsents?.functionalCookies !== "checked" &&
    intaCookieConsents?.advertisementCookies !== "checked") {
    m = merge(allScripts[1].scripts, allScripts[2].scripts);
} else if (intaCookieConsents?.functionalCookies === "checked" &&
    intaCookieConsents?.staticsticCookies === "checked") {
    m = allScripts[1].scripts;
} else if (intaCookieConsents?.functionalCookies === "checked" &&
    intaCookieConsents?.advertisementCookies === "checked") {
    m = allScripts[0].scripts;
} else if (intaCookieConsents?.advertisementCookies === "checked" &&
    intaCookieConsents?.staticsticCookies === "checked") {
    m = allScripts[2].scripts;
} else {
    m = merge(allScripts[0].scripts, allScripts[1].scripts, allScripts[2].scripts);
}
/* No `g` flag: global regex makes `.test()` advance `lastIndex`, so later URLs (e.g. bzrcdn.openai.com)
 * can spuriously fail to match even when patterns like `openai` / `oaiq` apply. */
notRequired = window.notRequired = new RegExp(m.join("|"), "i");
function ConsentsBlock(logo, textLanguage, btnText, datatype, img) {
    let p = "";
    if (window.location.host.indexOf("intastellarsolutions.com") == -1) {
        p = `<a class="inta-poweredBy" href='https://www.intastellarsolutions.com' target='_blank' rel='noopener' style="align-items: center; text-decoration: none;font-size: 11.5px; color: #000 !important; display: flex; justify-content: center;">powered by <img width="90px" height="40px" style="width: 170px !important; height: 40px !important;margin-left: 10px;" src="https://www.intastellarsolutions.com/assets/logos/intastellar-consents-logo.svg" alt="Intastellar Consents"></a>`;
    }
    if (img !== undefined && img != "") {
        return `
        <inta-consents-content class="intCookie_ConsentContainer-content yt-frame">
            <inta-consents-bg class="intCookie_ConsentContainer-bgIMG" inta-bg-img="${img}"></inta-consents-bg>
            <inta-consents-section class="intCookie_ConsentContainer-info">
                ${textLanguage}
                <button class='intastellarCookie-settings__btn --changePermission' onClick='updateCookiePreferenceOfBlockedIframes("${datatype}")' data-type='${datatype}'>${btnText}</button>
                ${p}
            </inta-consents-section>
        </inta-consents-content>
        `
    } else {
        return `
            <inta-consents-content class="intCookie_ConsentContainer-content">
                ${logo === null ? "" : `
                <inta-consents-logo class="intCookie_ConsentLogo-container">
                    <img src="${logo}" class="intCookie_ConsentLogo" alt="Company logo">
                </inta-consents-logo>
                `}
                
                <inta-consents-section class="intCookie_ConsentContainer-info">
                    ${textLanguage}
                    <button class='intastellarCookie-settings__btn --changePermission' onClick='updateCookiePreferenceOfBlockedIframes("${datatype}")' data-type='${datatype}'>${btnText}</button>
                    ${p}
                </inta-consents-section>
            </inta-consents-content>
        `
    }
}

/* Helper function to check class names */
function containsClass(element, searchString) {
    return element?.classList?.contains(searchString) || element?.className?.split(' ')?.some(cls => cls?.includes(searchString));
}

function loopBlock(addedNodes, script, logo) {
    addedNodes.forEach((frae) => {
        if (getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.advertisementCookies === "checked"
            && intaCookieConsents?.functionalCookies === "checked" && intaCookieConsents?.staticsticCookies === "checked") {
            return;
        }
        let settingsContent = document.createElement("inta-consents-iframe");
        if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && !intaCookieConsents?.advertisementCookies && script.type == "statics") {
            if (frae?.src?.indexOf("hs-sites.com") > -1) {
                frae?.parentElement?.replaceChild("", frae);
            }
        }
        if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && !intaCookieConsents?.advertisementCookies && script.type == "marketing") {
            if (containsClass(frae, "fb-") && frae.getAttribute("data-href")?.indexOf("facebook.com") > -1) {
                frae?.parentElement?.replaceChild(settingsContent, frae);
            }
            if (new RegExp(script.scripts.join("|"), "ig").test(frae.src) || frae?.className?.match(new RegExp(script.scripts.join("|"), "ig"))) {
                frae.sandbox = "";
                let ytIMG = "";
                let video_id = "";

                if (frae.src != undefined) {
                    if (frae.src.match("^(?:https?:)?//[^/]*(?:youtube(?:-nocookie)?\.com|youtu\.be).*[=/]([-\\w]{11})(?:\\?|=|&|$)")) {
                        video_id = frae?.src?.match("^(?:https?:)?//[^/]*(?:youtube(?:-nocookie)?\.com|youtu\.be).*[=/]([-\\w]{11})(?:\\?|=|&|$)")?.pop();
                        if (video_id && !frae?.hasAttribute("inta-yt-placeholder-img")) {
                            ytIMG = "https://img.youtube.com/vi/" + video_id + "/maxresdefault.jpg";
                        } else if (frae?.hasAttribute("inta-yt-placeholder-img")) {
                            ytIMG = frae?.getAttribute("inta-yt-placeholder-img");
                        }
                    } else {
                        if (frae?.hasAttribute("inta-yt-placeholder-img")) {
                            ytIMG = frae?.getAttribute("inta-yt-placeholder-img");
                        }
                    }
                }
                let a = document.createElement('a');
                a.href = frae.src;
                let externalDomain = a.hostname;

                inta_marketingCookieList.forEach((cookie) => {
                    var i = 0,
                        d = externalDomain,
                        p = d.split(".")

                    d = p.slice(-1 - ++i).join(".");
                    externalDomain = d;

                    if (cookie?.domains?.includes(externalDomain)) {
                        externalDomain = cookie.vendor;
                    }
                })
                if (frae.src !== window.INTA?.settings?.partnerDomain) {
                    frae.src = "about:blank";
                }
                let copy = intaPickBlockedIframeStrings(externalDomain, frae, script.type, inta_marketingCookieList);
                let textLanguage = copy.textLanguage;
                let btnText = copy.btnText;
                if (!frae.classList.contains("trustpilot-widget")) {
                    settingsContent.setAttribute("data-src", a?.href);
                }
                settingsContent.classList.add("intCookie_ConsentContainer");
                if (ytIMG !== undefined && ytIMG != "") {
                    settingsContent.classList.add("yt-frame");
                }
                if (frae.classList.length > 0) {
                    settingsContent.setAttribute("data-class", frae.className);
                }
                settingsContent.innerHTML = ConsentsBlock(logo, textLanguage, btnText, "intMarketingCookies", ytIMG);

                if (frae.style.display != "none" && frae.src != undefined) {
                    frae?.parentElement?.replaceChild(settingsContent, frae);
                }

            }
        } else if (getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && !intaCookieConsents?.functionalCookies && script.type == "functional") {
            if (new RegExp(script.scripts.join("|"), "ig").test(frae.src)) {
                frae.sandbox = "";
                let a = document.createElement('a');
                a.href = frae.src;
                let externalDomain = a.hostname;

                inta_functionalCookieList.forEach((cookie) => {
                    var i = 0,
                        d = externalDomain,
                        p = d.split(".")

                    d = p.slice(-1 - ++i).join(".");
                    externalDomain = d;
                    if (cookie?.domains?.includes(externalDomain)) {
                        externalDomain = cookie.vendor;
                    }
                })

                let copy = intaPickBlockedIframeStrings(externalDomain, frae, script.type, inta_functionalCookieList);
                let textLanguage = copy.textLanguage;
                let btnText = copy.btnText;

                let settingsContent = document.createElement("inta-consents");
                settingsContent.classList.add("intCookie_ConsentContainer");
                settingsContent.setAttribute("data-src", a.href);
                settingsContent.innerHTML = ConsentsBlock(logo, textLanguage, btnText, "intFunctionalCookies");

                if (frae?.src?.indexOf("hs-sites.com") > -1) {
                    frae?.parentElement?.replaceChild("", frae);
                } else {
                    if (frae.style.display != "none" && frae.src != undefined) {

                        frae?.parentElement?.replaceChild(settingsContent, frae);
                    }

                }
            } else if (frae?.id?.indexOf("map") > -1 || frae?.id?.indexOf("google") > -1 && frae?.id?.indexOf("google_translate_element2") == -1) {
                let externalDomain = "www.google.com";
                inta_functionalCookieList.forEach((cookie) => {
                    var i = 0,
                        d = externalDomain,
                        p = d.split(".")

                    d = p.slice(-1 - ++i).join(".");
                    externalDomain = d;
                    if (cookie?.domains?.includes(externalDomain)) {
                        externalDomain = cookie.vendor;
                    }
                })

                let copy = intaPickBlockedIframeStrings(externalDomain, frae, script.type, inta_functionalCookieList);
                let textLanguage = copy.textLanguage;
                let btnText = copy.btnText;

                let settingsContent = document.createElement("inta-consents");
                settingsContent.classList.add("intCookie_ConsentContainer");

                settingsContent.innerHTML = ConsentsBlock(logo, textLanguage, btnText, "intFunctionalCookies");

                settingsContent.setAttribute("data-src", frae.src);
                if (frae?.src?.indexOf("hs-sites.com") > -1) {
                    frae?.parentElement?.replaceChild("", frae);
                } else {
                    if (frae.style.display != "none" && frae.src != undefined) {
                        frae.parentElement.replaceChild(settingsContent, frae);
                    }
                }
            } else if (frae?.id?.indexOf("google_translate_element2") > -1) {
                frae?.parentElement?.replaceChild("", frae);
            }
        }
    })
}

function blockBlockQuotes(tweet, script, logo) {
    if (tweet != " " && getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || !intaCookieConsents?.advertisementCookies && script.type == "marketing" && notRequired.test(tweet.className)) {
        let a = document.createElement('a');
        a.href = tweet.querySelector("a").href;
        let externalDomain = a.hostname;

        inta_marketingCookieList.forEach((cookie) => {
            var i = 0,
                d = externalDomain,
                p = d.split(".")

            d = p.slice(-1 - ++i).join(".");
            externalDomain = d;

            if (cookie?.domains?.includes(externalDomain)) {
                externalDomain = cookie.vendor;
            }
        })

        let copy = intaPickBlockedIframeStrings(externalDomain, tweet, script.type, inta_marketingCookieList);
        let textLanguage = copy.textLanguage;
        let btnText = copy.btnText;
        let settingsContent = document.createElement("inta-consents");
        settingsContent.classList.add("intCookie_ConsentContainer");
        settingsContent.innerHTML = ConsentsBlock(logo, textLanguage, btnText, "intMarketingCookies");

        settingsContent.setAttribute("data-src", a.href);
        if (tweet.src.indexOf("hs-sites.com") > -1) {
            tweet.parentElement.replaceChild("", tweet);
        } else {
            if (tweet.style.display != "none" && tweet.src != undefined) {
                tweet.parentElement.replaceChild(settingsContent, tweet);

            }
        }
    }
}
function restartObserver() {
    // Disconnect any existing observer
    if (window.currentObserver) {
        window.currentObserver.disconnect();
    }

    // Create a new observer with updated consent settings
    window.currentObserver = checkCookieStatus();

    // Process any existing blocked content that should now be allowed
    processExistingScripts();

}

let beforeScriptExecuteListener = function (event, node) {
    let src = node.src || "";

    if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
        || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
        || !FunctionalCheckbox?.checked || !StaticsCheckBox?.checked || !MarketingCheckBox?.checked
    ) {
        if (
            src.indexOf(window.location.hostname) == -1
            && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
        ) {
            if (
                notRequired.test(src)
            ) {
                node.defer = true;
                node.async = true;
                node.type = "text/blocked";
                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
            }
        } else if (src.indexOf(window.location.hostname) == -1
            && src.indexOf("jquery") > -1) {
            node.type = "text/javascript";
            node.defer = false;
            node.async = false;
        } else {
            node.type = "text/javascript";
            /* if(document.querySelector(scriptTag) === null){
                node.parentElement.appendChild(scriptTag);
            } */
        }

        if (
            notRequired.test(node.innerText)
            && node.innerText.toLowerCase().indexOf("elementor") == -1
        ) {
            node.defer = true;
            node.async = true;
            node.type = "text/blocked";
            /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
        } else {
            /* if(document.querySelector(scriptTag) === null){
                node.parentElement.appendChild(scriptTag);
            } */
        }
    } else if (intaCookieConsents?.functionalCookies === "checked" &&
        intaCookieConsents?.advertisementCookies === "checked" &&
        intaCookieConsents?.staticsticCookies === "checked"
        || FunctionalCheckbox?.checked && StaticsCheckBox?.checked && MarketingCheckBox?.checked) {
        node.type = "text/javascript";
    }

    if (node.getAttribute("type") === "text/blocked")
        event.preventDefault();
    node.removeEventListener(
        "beforescriptexecute",
        (e, node) => beforeScriptExecuteListener(e, node)
    );

    // Disconnect the observer if it exists
    if (window.currentObserver) {
        window.currentObserver.disconnect();
    }
};

function checkCookieStatus() {
    if (isGtmMode) {
        /* console.log("Observer disabled in GTM mode"); */
        return null; // Return null instead of creating an observer
    }
    /* To get anonymous cookie banner usage */
    /* - - - Observer - - - */

    let __intaObserverPendingMutations = [];
    let __intaObserverDebounceTimer = null;
    let observer = new MutationObserver((mutations) => {
        for (let mi = 0; mi < mutations.length; mi++) {
            __intaObserverPendingMutations.push(mutations[mi]);
        }
        if (__intaObserverDebounceTimer !== null) {
            clearTimeout(__intaObserverDebounceTimer);
        }
        __intaObserverDebounceTimer = setTimeout(function () {
            __intaObserverDebounceTimer = null;
            let batch = __intaObserverPendingMutations;
            __intaObserverPendingMutations = [];
            requestAnimationFrame(() => {
                batch.forEach(({ addedNodes }) => {
                addedNodes.forEach((node) => {

                    if (node.nodeType === 1 && node.tagName === "DIV" || node.nodeType === 1 && node.tagName === "IFRAME") {
                        allScripts.map((script) => {
                            intaEnsureBlockedIframeMessagesLoaded();
                            let INTAlogo = (window.INT) ? window.INT.settings.logo : (window.INTA?.settings?.logo) ? window.INTA?.settings?.logo : null;
                            loopBlock(addedNodes, script, INTAlogo);
                        })
                    }

                    if (node.nodeType === 1 && node.tagName === "BLOCKQUOTE") {
                        allScripts.map((script) => {
                            addedNodes.forEach((tweet) => {
                                intaEnsureBlockedIframeMessagesLoaded();
                                let INTAlogo = (window.INT) ? window.INT.settings.logo : (window.INTA?.settings?.logo) ? window.INTA?.settings?.logo : null;
                                blockBlockQuotes(tweet, script, INTAlogo);
                            });
                        });
                    }

                    if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                        || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == "") {
                        if (node.nodeType === 1 && node.tagName === "LINK") {
                            addedNodes.forEach((link) => {
                                let linkSrc = link.href;
                                if (notRequired.test(linkSrc)) {
                                    link.disabled = true;
                                }
                            })
                        }
                    }

                    if (node.nodeType === 1 && node.tagName === "SCRIPT" && node.type !== 'application/ld+json' && node.innerText.indexOf("window.INTA") == -1 && node.innerText.indexOf("window.INT") == -1 && node.innerText.indexOf("window.INTA") == -1 && node.innerText.toLowerCase().indexOf("elementor") == -1 && node.innerText.toLowerCase().indexOf("chic_lite_data") == -1 && node.innerText.toLowerCase().indexOf("mailchimp_public_data") == -1 && node.innerText.toLowerCase().indexOf("monsterinsights_frontend") == -1) {
                        let src = node.src || "";


                        node.removeAttribute("charset");
                        addedNodes.forEach((node) => {

                            src = node.src;
                            if (src.indexOf(window.location.hostname) == -1) {
                                if (src.trim() === "") {
                                    return;
                                }
                                window.foundScripts.push(src);
                                // Filter out scripts that are empty or contain only whitespace

                            }

                            if (intaCookieConsents?.advertisementCookies === "checked" || intaCookieConsents?.functionalCookies === "checked" || intaCookieConsents?.staticsticCookies === "checked"
                                || FunctionalCheckbox?.checked || StaticsCheckBox?.checked || MarketingCheckBox?.checked
                            ) {
                                node.type = "text/javascript";
                                return;
                            }



                            if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                                || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
                                || !FunctionalCheckbox?.checked && !StaticsCheckBox?.checked && !MarketingCheckBox?.checked
                            ) {
                                if (
                                    src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
                                ) {
                                    if (
                                        notRequired.test(src)
                                    ) {
                                        node.type = "text/blocked";
                                        node.defer = true;
                                        node.async = true;

                                        /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/

                                        /* deleteAllCookies(); */
                                    }
                                } else if (src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == 1) {
                                    node.type = "text/javascript";
                                    node.defer = false;
                                    node.async = false;
                                }

                                if (
                                    notRequired.test(node.innerText)
                                ) {
                                    node.defer = true;
                                    node.async = true;
                                    node.type = "text/blocked";
                                    /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                    /* deleteAllCookies(); */
                                }
                            } else if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1
                                || intaCookieConsents?.advertisementCookies == "false" &&
                                getCookie(int_hideCookieBannerName) != "" &&
                                getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 &&
                                intaCookieConsents?.functionalCookies == "false" &&
                                getCookie(int_hideCookieBannerName) != "" &&
                                getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 &&
                                intaCookieConsents?.staticsticCookies == "false" ||
                                intaCookieConsents?.advertisementCookies == "null" &&
                                intaCookieConsents?.functionalCookies == "null" &&
                                intaCookieConsents?.staticsticCookies == "null"
                                || intaCookieConsents?.advertisementCookies == "" &&
                                intaCookieConsents?.functionalCookies == "" &&
                                intaCookieConsents?.staticsticCookies == ""
                                || !FunctionalCheckbox?.checked &&
                                !StaticsCheckBox?.checked &&
                                !MarketingCheckBox?.checked
                            ) {
                                if (
                                    src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
                                ) {
                                    if (
                                        notRequired.test(src)
                                    ) {
                                        node.type = "text/blocked";
                                        node.defer = true;
                                        node.async = true;
                                        /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                    }
                                } else if (src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == 1) {
                                    node.type = "text/javascript";
                                    node.defer = false;
                                    node.async = false;
                                }
                                if (
                                    notRequired.test(node.innerText)
                                    && node.innerText.toLowerCase().indexOf("elementor") == -1
                                ) {
                                    node.type = "text/blocked";
                                    node.defer = true;
                                    node.async = true;
                                    /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                }
                            }

                            if (node.getAttribute("type") === "text/blocked") {
                                node.addEventListener(
                                    "beforescriptexecute",
                                    (e) => beforeScriptExecuteListener(e, node)
                                );
                            }
                        });
                    } else if (node.nodeType === 1 && node.tagName === "NOSCRIPT" && node.type !== 'application/ld+json' && node.innerText.indexOf("window.INTA") == -1 && node.innerText.indexOf("window.INT") == -1 && node.innerText.toLowerCase().indexOf("elementor") == -1) {
                        if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                            || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
                            || FunctionalCheckbox?.checked && StaticsCheckBox?.checked && MarketingCheckBox?.checked
                        ) {

                            if (
                                notRequired.test(node.innerText)
                                && node.innerText.toLowerCase().indexOf("elementor") == -1
                            ) {
                                node.defer = true;
                                node.async = true;
                                node.type = "text/blocked";
                                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                /* deleteAllCookies(); */
                            }
                        } else if (intaCookieConsents?.functionalCookies == "false" && intaCookieConsents?.advertisementCookies == "false" && intaCookieConsents?.staticsticCookies == "false"
                            || !FunctionalCheckbox?.checked && !StaticsCheckBox?.checked && !MarketingCheckBox?.checked
                        ) {

                            if (
                                notRequired.test(node.innerText)
                                && node.innerText.toLowerCase().indexOf("elementor") == -1
                            ) {
                                node.defer = true;
                                node.async = true;
                                node.type = "text/blocked";
                                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                            } else {
                                /* node.parentElement.appendChild(node); */
                            }
                        } else if (intaCookieConsents?.functionalCookies === "checked" &&
                            intaCookieConsents?.advertisementCookies === "checked" &&
                            intaCookieConsents?.staticsticCookies === "checked" ||
                            FunctionalCheckbox?.checked &&
                            StaticsCheckBox?.checked &&
                            MarketingCheckBox?.checked

                        ) {
                            node.type = "text/javascript";
                        }
                    }
                });
            });
        });
        }, 80);
    });
    startObserving(observer, document.documentElement);
    return observer;

}

function startObserving(observer) {
    observer.observe(document.documentElement, {
        childList: !0,
        subtree: !0,
        attributes: true,
        attributeFilter: ["src", "href", "type", "value", "checked", "innerText"],
    })
}

window.inta_marketingCookieList = window.inta_marketingCookieList || [];
window.inta_functionalCookieList = window.inta_functionalCookieList || [];

function recordCookie(value) {
    window.__INTA__COOKIE_EVENTS__ = window.__INTA__COOKIE_EVENTS__ || [];
    window.__INTA__COOKIE_EVENTS__.push(value);
    if (typeof window.__intaRecordCookieImpl === "function") {
        return window.__intaRecordCookieImpl(value);
    }
    window.__intaPendingCookieRecords = window.__intaPendingCookieRecords || [];
    window.__intaPendingCookieRecords.push(value);
}

function intaLoadUcCore() {
    if (window.__intaUcCoreReady || window.__intaUcCoreLoading) {
        return;
    }
    window.__intaUcCoreLoading = true;
    var base = (typeof window.INTA !== "undefined" && window.INTA.settings && window.INTA.settings.coreUrl)
        || "https://consents.cdn.intastellarsolutions.com/uc-core.js";
    if (typeof intastellarDevMode !== "undefined" && intastellarDevMode) {
        base = "../../dev/uc-core.dev.js";
    }
    try {
        var preload = document.createElement("link");
        preload.rel = "preload";
        preload.as = "script";
        preload.href = base;
        preload.crossOrigin = "anonymous";
        (document.head || document.documentElement).appendChild(preload);
    } catch (ePre) { /* ignore */ }
    var s = document.createElement("script");
    s.src = base;
    s.async = true;
    s.onload = function () {
        window.__intaUcCoreReady = true;
        window.__intaUcCoreLoading = false;
        var pending = window.__intaPendingCookieRecords;
        if (pending && pending.length && typeof window.__intaRecordCookieImpl === "function") {
            for (var i = 0; i < pending.length; i++) {
                window.__intaRecordCookieImpl(pending[i]);
            }
            window.__intaPendingCookieRecords = [];
        }
        try {
            window.dispatchEvent(new CustomEvent("inta:uc-core-ready"));
        } catch (e) { /* ignore */ }
    };
    s.onerror = function () {
        window.__intaUcCoreLoading = false;
    };
    if (typeof intaAppendToDocumentHead === "function") {
        intaAppendToDocumentHead(s);
    } else {
        (document.head || document.documentElement).appendChild(s);
    }
}

if (!isGtmMode) {
    checkCookieStatus();
}

intaLoadUcCore();
