/*
 *  uc-boot — sync CMP guard (loaded as uc.js). Loads uc-core.js async.
 *  Generated by scripts/build-uc-split.mjs — edit dev/gdpr.dev.js, then re-run.
 */
/*
 *  Cookie Consents Banner by Intastellar Solutions, International
 *  intastellarsolutions.com/gdpr-cookiebanner
 *  consents.cdn.intastellarsolutions.com/uc.js
 *  @copy 2022-2025 Intastellar Solutions, International
 *
*/
// --- Cross-site Consent Tracking ---
// Request consent state for a user
// Request consent state for a user
function requestConsentState(userId, rootDomain, partnerDomains = []) {
    consentIframe.contentWindow.postMessage({ type: 'getConsent', userId, rootDomain, partnerDomains }, 'https://consents.cdn.intastellarsolutions.com');
}

// Set consent state for a user
function setConsentState(userId, consents, rootDomain, partnerDomains = []) {
    consentIframe.contentWindow.postMessage({ type: 'setConsent', userId, consents, rootDomain, partnerDomains }, 'https://consents.cdn.intastellarsolutions.com');
    // VWO consent update
    updateVwoConsent(consents);
}

/**
 * Shopify: `sale_of_data` is separate from marketing/analytics/preferences (CCPA-style opt-out).
 * Only send `sale_of_data: false` when the visitor used the dedicated opt-out flow (`ccpa_opt_out`).
 * Do not map marketing cookies to sale_of_data — see Shopify Customer Privacy docs.
 * @see https://shopify.dev/docs/api/customer-privacy#collect-and-register-data-sale--sharing-opt-out
 */
function intaShopifyMergePayloadWithCcpaSaleOptOut(payload) {
    if (!payload || typeof payload !== "object") {
        return payload;
    }
    let out = Object.assign({}, payload);
    try {
        if (localStorage.getItem("ccpa_opt_out") === "true") {
            out.sale_of_data = false;
        }
    } catch (e) {
        /* ignore */
    }
    return out;
}

/* --- Shopify setTrackingConsent coalescing (one network write per burst + skip identical payload) --- */
let intaShopifyCoalesceTimer = null;
let intaShopifyCoalescePending = null;
let intaShopifyCoalesceCallbacks = [];
let intaShopifyLastSetTrackingConsentJson = null;
let intaShopifyFlushApiMisses = 0;

function intaShopifyStableConsentPayloadJson(p) {
    if (!p || typeof p !== "object") {
        return "";
    }
    let keys = ["analytics", "marketing", "preferences", "sale_of_data"].filter(function (k) {
        return Object.prototype.hasOwnProperty.call(p, k);
    });
    let o = {};
    for (let i = 0; i < keys.length; i++) {
        o[keys[i]] = p[keys[i]];
    }
    return JSON.stringify(o);
}

function intaShopifyShallowMergeConsentPatch(target, patch) {
    let base = target && typeof target === "object" ? Object.assign({}, target) : {};
    if (!patch || typeof patch !== "object") {
        return base;
    }
    if ("analytics" in patch) {
        base.analytics = patch.analytics;
    }
    if ("marketing" in patch) {
        base.marketing = patch.marketing;
    }
    if ("preferences" in patch) {
        base.preferences = patch.preferences;
    }
    if ("sale_of_data" in patch) {
        base.sale_of_data = patch.sale_of_data;
    }
    return base;
}

function intaShopifyRunCoalescedCallbacks(arr) {
    let list = arr || [];
    for (let i = 0; i < list.length; i++) {
        try {
            if (typeof list[i] === "function") {
                list[i]();
            }
        } catch (e) {
            /* ignore */
        }
    }
}

function intaShopifyFlushQueuedSetTrackingConsent() {
    intaShopifyCoalesceTimer = null;
    if (intaShopifyCoalescePending == null || typeof intaShopifyCoalescePending !== "object") {
        intaShopifyRunCoalescedCallbacks(intaShopifyCoalesceCallbacks.splice(0));
        return;
    }

    let merged = intaShopifyMergePayloadWithCcpaSaleOptOut(Object.assign({}, intaShopifyCoalescePending));
    let api = window.Shopify && window.Shopify.customerPrivacy;

    if (typeof api?.setTrackingConsent !== "function") {
        let canRetry = typeof window.Shopify?.loadFeatures === "function";
        if (!canRetry || intaShopifyFlushApiMisses > 80) {
            intaShopifyCoalescePending = null;
            intaShopifyFlushApiMisses = 0;
            intaShopifyRunCoalescedCallbacks(intaShopifyCoalesceCallbacks.splice(0));
            return;
        }
        intaShopifyFlushApiMisses++;
        intaShopifyCoalesceTimer = setTimeout(intaShopifyFlushQueuedSetTrackingConsent, 100);
        return;
    }
    intaShopifyFlushApiMisses = 0;

    let json = intaShopifyStableConsentPayloadJson(merged);
    if (json === intaShopifyLastSetTrackingConsentJson) {
        intaShopifyCoalescePending = null;
        intaShopifyRunCoalescedCallbacks(intaShopifyCoalesceCallbacks.splice(0));
        return;
    }

    intaShopifyCoalescePending = null;
    let cbs = intaShopifyCoalesceCallbacks.splice(0);

    try {
        api.setTrackingConsent(merged, function () {
            intaShopifyLastSetTrackingConsentJson = json;
            intaShopifyRefreshCustomerPrivacyState(null);
            intaShopifyRunCoalescedCallbacks(cbs);
        });
    } catch (e) {
        intaShopifyRunCoalescedCallbacks(cbs);
    }
}

function intaShopifyEnqueueSetTrackingConsent(payload, onDone) {
    try {
        intaShopifyCoalescePending = intaShopifyShallowMergeConsentPatch(intaShopifyCoalescePending, payload);
        if (typeof onDone === "function") {
            intaShopifyCoalesceCallbacks.push(onDone);
        }
        if (intaShopifyCoalesceTimer != null) {
            clearTimeout(intaShopifyCoalesceTimer);
        }
        intaShopifyCoalesceTimer = setTimeout(intaShopifyFlushQueuedSetTrackingConsent, 0);
    } catch (e) {
        /* ignore */
    }
}

/**
 * Shopify Customer Privacy: all writes go through the coalescing queue (one setTrackingConsent per tick / deduped).
 */
function intaShopifySetTrackingConsentSafe(consents, onDone) {
    try {
        if (!consents || typeof consents !== "object") {
            if (typeof onDone === "function") {
                onDone();
            }
            return;
        }
        intaShopifyEnqueueSetTrackingConsent(Object.assign({}, consents), onDone);
    } catch (e) {
        /* non-Shopify or API not ready */
    }
}

let allScripts = window.allScripts = [
    {
        /* Analytics Scripts which are beeing blocked */
        /* "([\-\.]clarity+)", */
        type: "statics",
        scripts: [
            "(mixpanel)",
            "([\-\.]googleoptimize+)",
            "([\-\.]piwik+)",
            "([\-\.]matomo+)",
            "([\-\.]bing+)",
            "([\-\.]slideshare+)",
            "([\-\.]siteimproveanalytics+)",
            "([\-\.]hotjar+)",
            "([\-\.]snapchat)",
            "([\-\.]contentsquare)",
            "([\-\.]6sc)",
            "([\-\.]nr-data)",
            "([\-\.]2o7)",
            "([\-\.]hackerone)",
            "([\-\.]gstatic)",
            "([\-\.]webtrends)",
            "([\-\.]webtrendslive)",
            "([\-\.]amplitude)",
            "([\-\.]adobe)",
            "([\-\.]mxpnl)",
            "([\-\.]mixpanel)",
            "([\-\.]gstatics+)",
            "([\-\.]adobedtm)",
            "([\-\.]adobedc)",
            "([\-\.]qualtrics+)",
            "([\-\.]pardot+)",
            "([\-\.]poultons+)",
            "([\-\.]chartbeat+)",
            "([\-\.]consensu+)",
            "([\-\.]clarity+)",
            "([\-\.]clarity-cdn+)",
            "([\-\.]vwo+)",
            "([\-\.]ip-only+)",
            "([\-\.]ggpht+)",
            "([\-\.]clearbitjs+)",
            "([\-\.]clearbitscripts+)",
            "([\-\.]optimizely+)",
            "([\-\.]segment+)",
            "([\-\.]quantserve+)[a-z]{2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    },
    {
        /* Marketing Scripts which are beeing blocked */
        /* 
            "([\-\.]googlesyndication+)",
            "([\-\.]googletagservices+)",
            "([\-\.]googleadservices+)",
            "([\-\.]omnisnippet+)",
        */
        type: "marketing",
        scripts: [
            "(_linkedin_partner_id|_linkedin_data_partner_ids|mailchimp|lntrk|twitter|instagram|trustpilot|chic_lite_data|openai|oaiq|bzrcdn\\.openai)",
            "([\-\.]twitter+)",
            "([\-\.]ads-twitter+)",
            "([\-\.]casalemedia+)",
            "(chimpstatic+)",
            "([\-\.]trustpilot+)",
            "([\-\.]mailchimp+)",
            "([\-\.]linkedin+)",
            "([\-\.]bing+)",
            "([\-\.]licdn+)",
            "([\-\.]amazon-adsystem+)",
            "([\-\.]adfrom+)",
            "([\-\.]demdex+)",
            "([\-\.]criteo+)",
            "([\-\.]clearbitjs+)",
            "([\-\.]clearbitscripts+)",
            "([\-\.]instagram+)",
            "([\-\.]stickyadstv+)",
            "([\-\.]mookie1+)",
            "([\-\.]doubleclick+)",
            "([\-\.]bidswitch+)",
            "([\-\.]jnqsge+)",
            "([\-\.]syuh+)",
            "([\-\.]youtube+)",
            "([\-\.]vimeo+)",
            "([\-\.]ninthdecimal+)",
            "([\-\.]casalemedia+)",
            "([\-\.]adsymptotic+)",
            "([\-\.]tremorhub+)",
            "([\-\.]agkn+)",
            "([\-\.]myvisualiq+)",
            "([\-\.]exelator+)",
            "([\-\.]openx+)",
            "([\-\.]adsrvr+)",
            "([\-\.]justpremium+)",
            "([\-\.]ants+)",
            "([\-\.]bluekai+)",
            "([\-\.]revcontent+)",
            "([\-\.]outbrain+)",
            "([\-\.]adscale+)",
            "([\-\.]pdst+)",
            "([\-\.]yahoo+)",
            "([\-\.]advertising+)",
            "([\-\.]adnxs+)",
            "([\-\.]scdn+)",
            "([\-\.]spotify+)",
            "([\-\.]facebook+)",
            "([\-\.]pinterest+)",
            "([\-\.]adform+)",
            "([\-\.]adnxs+)",
            "([\-\.]advertising+)",
            "([\-\.]adtech+)",
            "([\-\.]soundestlink+)",
            "([\-\.]soundest+)",
            "([\-\.]soundestvid+)",
            "([\-\.]soundestform+)",
            "([\-\.]tiktok+)",
            "([\-\.]taboola+)",
            "([\-\.]hubspot+)",
            "([\-\.]openai+)",
            /* "([\-\.]hs-sites+)", */
            "([a-z]+){2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    },
    {
        /* Functional Scripts which are beeing blocked */
        type: "functional",
        scripts: [
            "(maps.google.com+)",
            "(www.google.com/maps/+)",
            "([\-\.]googleapis+)",
            "([\-\.]gstatics+)",
            "([\-\.]cludo+)",
            "([\-\.]qbrick+)",
            "([\-\.]klarna+)",
            "([\-\.]paypal+)",
            "([\-\.]usersnap+)",
            "([\-\.]zoom+)",
            "([\-\.]cdnjs+)",
            "([\-\.]jsdelivr+)",
            "([\-\.]disqus+)([a-z]+){2,5}(:[0-9]{1,5})?(\\\\.*)"
        ]
    }
];
let __intaCompiledScriptPatterns = null;
function intaGetCompiledScriptPatterns() {
    if (__intaCompiledScriptPatterns) {
        return __intaCompiledScriptPatterns;
    }
    __intaCompiledScriptPatterns = [];
    for (let i = 0; i < window.allScripts.length; i++) {
        let scriptType = window.allScripts[i].type;
        let patterns = window.allScripts[i].scripts;
        let regexes = [];
        for (let j = 0; j < patterns.length; j++) {
            try {
                regexes.push(new RegExp(patterns[j], "i"));
            } catch (eCompile) { /* ignore invalid regex */ }
        }
        __intaCompiledScriptPatterns.push({ type: scriptType, regexes: regexes });
    }
    return __intaCompiledScriptPatterns;
}
let __intaCookieEventFlushTimer = null;
let __intaCookieEventPendingByKey = new Map();
let INTA_COOKIE_EVENT_DEBOUNCE_MS = 5000;
let INTA_COOKIE_EVENT_MIN_FLUSH_GAP_MS = 250;
let INTA_COOKIE_EVENT_MAX_BATCH = 50;
let INTA_COOKIE_EVENTS_URL = 'https://consents.intastellarsolutions.com/api/v1/cookie-events';

// Listen for consent state response
window.addEventListener('message', (event) => {
    if (event.origin !== 'https://consents.cdn.intastellarsolutions.com') return;
    if (event.data.type === 'consentState') {
        // Integrate with your banner logic
        window.intaCookieConsents = event.data.consents;
        intaShopifySetTrackingConsentFromConsentsObject(event.data.consents);
        // Optionally, update checkboxes or UI elements
        if (typeof updateConsentUI === 'function') {
            updateConsentUI(event.data.consents);
        }
        if (typeof window.intaApplyCmpVisibilityFromCookie === 'function') {
            window.intaApplyCmpVisibilityFromCookie();
        }
        console.log('Received consent state:', event.data.consents);
    }
});

window["optimizely"] = window["optimizely"] || [];
window["optimizely"].push({
    "type": "optOut",
    "isOptOut": true
});

window.pintrk = window.pintrk || function () {
    window.pintrk.queue.push(Array.prototype.slice.call(arguments));
};
window.pintrk.queue = window.pintrk.queue || [];

pintrk('setconsent', false);

window.VWO = window.VWO || [];
window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
window.VWO.init(2); // default to pending
window.INTA = window.INTA || {};
window.INTA.observedCookieSource = 'unknown';
// --- VWO Cookie Consent Integration (latest, per docs) ---
function updateVwoConsent(consents) {
    // VWO expects: 1 = accepted, 2 = pending, 3 = rejected
    // VWO runs when marketing OR statistical (analytics) cookies are accepted — not only marketing.
    var state = 2;
    if (!consents) {
        window.VWO = window.VWO || [];
        window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
        window.VWO.init(state);
        return;
    }
    function granted(v) {
        return v === true || v === "checked";
    }
    function denied(v) {
        return v === false || v === "unchecked";
    }
    var marketingOn = granted(consents.advertisementCookies) || consents.marketing === true;
    var statsOn = granted(consents.staticsticCookies) || consents.analytics === true;
    var marketingOff = denied(consents.advertisementCookies) || consents.marketing === false;
    var statsOff = denied(consents.staticsticCookies) || consents.analytics === false;

    if (marketingOn || statsOn) {
        state = 1;
    } else if (marketingOff && statsOff) {
        state = 3;
    } else {
        state = 2;
    }
    window.VWO = window.VWO || [];
    window.VWO.init = window.VWO.init || function (s) { window.VWO.consentState = s; };
    window.VWO.init(state);
    if (typeof window.VWO.onVariationApplied === 'function') {
        window.location.reload();
    }
}
// --- End VWO Cookie Consent Integration ---

/**
 * True when we should run WP Consent API integration (`wp_set_consent`, dataLayer mirror, cookie sync).
 * Requires `wp_set_consent` from WordPress. Set `INTA.settings.wpConsentApi = false` (before or early after
 * the script) when Google Advanced Consent Mode must be authoritative via `gtag`/GTM only — bridges such as
 * Site Kit that map WP cookies → Consent Mode can otherwise fight Intastellar’s updates.
 * @see https://wpconsentapi.org
 */
function intaWpConsentApiActive() {
    if (typeof wp_set_consent !== "function") {
        return false;
    }
    try {
        const s = window.INTA && window.INTA.settings;
        if (s && s.wpConsentApi === false) {
            return false;
        }
    } catch (e) { /* ignore */ }
    return true;
}

/** Google Consent Mode / gtag values → treat as granted (case-insensitive; tolerate common aliases). */
function intaWpConsentStorageIsGranted(value) {
    if (value === true) {
        return true;
    }
    if (value == null || value === false) {
        return false;
    }
    const s = String(value).toLowerCase();
    return s === "granted" || s === "grant" || s === "allow";
}

/**
 * CMP: `window.wp_consent_type = 'optin'` and `wp_consent_type_defined` on document (once per page when API is active).
 * @see https://wpconsentapi.org
 */
function intaWpEnsureConsentTypeOptinAnnouncedOnce() {
    if (!intaWpConsentApiActive() || window._intaWpConsentTypeDefinedSent) {
        return;
    }
    window._intaWpConsentTypeDefinedSent = true;
    try {
        window.wp_consent_type = "optin";
    } catch (e) { /* ignore */ }
    try {
        if (typeof document !== "undefined" && document.dispatchEvent) {
            document.dispatchEvent(new CustomEvent("wp_consent_type_defined"));
        }
    } catch (e) { /* ignore */ }
}

/**
 * When gtag pushes `consent` / `update`, mirror storage keys into `wp_set_consent`.
 * Does not dispatch a separate batched `wp_listen_for_consent_change` — each `wp_set_consent`
 * already fires the WP Consent API listener; an extra batched event can make Site Kit run a second gtag pass.
 * No-op unless `wp_set_consent` exists.
 * @see https://wpconsentapi.org
 */
function intaWpSetConsentFromGtagUpdateParams(params) {
    if (!intaWpConsentApiActive()) {
        return;
    }
    intaWpEnsureConsentTypeOptinAnnouncedOnce();
    const p = params && typeof params === "object" ? params : {};
    const lvl = (key) => (intaWpConsentStorageIsGranted(p[key]) ? "allow" : "deny");
    if ("functionality_storage" in p) {
        const fn = lvl("functionality_storage");
        wp_set_consent("functional", fn);
        wp_set_consent("preferences", fn);
    }
    if ("analytics_storage" in p) {
        const st = lvl("analytics_storage");
        wp_set_consent("statistics", st);
        wp_set_consent("statistics-anonymous", st);
    }
    if ("ad_storage" in p || "ad_user_data" in p || "ad_personalization" in p || "personalization_storage" in p) {
        const mk = (intaWpConsentStorageIsGranted(p.ad_storage) || intaWpConsentStorageIsGranted(p.ad_user_data) || intaWpConsentStorageIsGranted(p.ad_personalization) || intaWpConsentStorageIsGranted(p.personalization_storage))
            ? "allow"
            : "deny";
        wp_set_consent("marketing", mk);
    }
}

/**
 * Mirror consent from a single dataLayer item (Arguments object, array, or spread push).
 * Only handles `consent` / `update` (not `default`), so regional GTM defaults do not overwrite WP cookies incorrectly.
 */
function intaWpTryConsentUpdateFromDataLayerItem(item) {
    if (item == null) {
        return;
    }
    if (typeof item === "object" && !Array.isArray(item)) {
        const t0 = item[0];
        const t1 = item[1];
        const t2 = item[2];
        if (t0 === "consent" && t1 === "update" && t2 != null && typeof t2 === "object" && !Array.isArray(t2)) {
            intaWpSetConsentFromGtagUpdateParams(t2);
        }
    }
}

function intaWpTryConsentUpdateFromDataLayerPushArgs(pushArgs) {
    if (!intaWpConsentApiActive() || !pushArgs || pushArgs.length === 0) {
        return;
    }
    for (let i = 0; i < pushArgs.length; i++) {
        intaWpTryConsentUpdateFromDataLayerItem(pushArgs[i]);
    }
    if (pushArgs.length >= 3
        && pushArgs[0] === "consent"
        && pushArgs[1] === "update"
        && pushArgs[2] != null
        && typeof pushArgs[2] === "object"
        && !Array.isArray(pushArgs[2])) {
        intaWpSetConsentFromGtagUpdateParams(pushArgs[2]);
    }
}

/**
 * Keep our wrapper as the outermost `dataLayer.push`: GTM often replaces `push` after this script runs.
 * Mirroring runs inside the wrapper; `intaWpTryConsentUpdateFromDataLayerPushArgs` no-ops until `wp_set_consent` exists.
 */
function intaWpEnsureDataLayerPushMirrorBound() {
    const dl = window.dataLayer;
    if (!dl || typeof dl.push !== "function") {
        return;
    }
    const wrapped = dl._intaWpMirrorWrappedPush;
    if (wrapped && dl.push === wrapped) {
        return;
    }
    const upstream = dl.push;
    function intaWpMirrorWrappedPush() {
        window._intaWpDlPushDepth = (window._intaWpDlPushDepth || 0) + 1;
        const depthAtEntry = window._intaWpDlPushDepth;
        try {
            const ret = intaWpMirrorWrappedPush._upstream.apply(dl, arguments);
            // Site Kit (and others) listen to `wp_listen_for_consent_change` and call `gtag` → `dataLayer.push`
            // again. Only mirror the outermost push so we do not recurse until stack overflow.
            if (depthAtEntry === 1) {
                try {
                    intaWpTryConsentUpdateFromDataLayerPushArgs(Array.prototype.slice.call(arguments));
                } catch (e2) { /* ignore */ }
            }
            return ret;
        } finally {
            window._intaWpDlPushDepth--;
        }
    }
    intaWpMirrorWrappedPush._upstream = upstream;
    dl._intaWpMirrorWrappedPush = intaWpMirrorWrappedPush;
    dl.push = intaWpMirrorWrappedPush;
}

function intaWpInstallDataLayerConsentMirror() {
    const dl = window.dataLayer;
    if (!dl || typeof dl.push !== "function") {
        return;
    }
    if (!dl._intaWpMirrorSchedule) {
        dl._intaWpMirrorSchedule = true;
        const rebind = function () {
            intaWpEnsureDataLayerPushMirrorBound();
        };
        if (typeof window !== "undefined" && window.addEventListener) {
            window.addEventListener("load", rebind);
        }
        let n = 0;
        const id = setInterval(function () {
            rebind();
            if (++n >= 50) {
                clearInterval(id);
            }
        }, 100);
    }
    intaWpEnsureDataLayerPushMirrorBound();
}

/**
 * Apply WP Consent API cookies from Intastellar checkbox choices (works even when GTM owns `dataLayer.push` / `gtag`).
 * functional → `functional` + `preferences`; statistics → `statistics` + `statistics-anonymous`; marketing → `marketing`.
 */
function intaWpApplyConsentFromIntastellarChoices(functionalChecked, statisticsChecked, marketingChecked) {
    if (!intaWpConsentApiActive()) {
        return;
    }
    intaWpEnsureConsentTypeOptinAnnouncedOnce();
    const prefs = functionalChecked ? "allow" : "deny";
    const stats = statisticsChecked ? "allow" : "deny";
    const mkt = marketingChecked ? "allow" : "deny";
    wp_set_consent("functional", prefs);
    wp_set_consent("preferences", prefs);
    wp_set_consent("statistics", stats);
    wp_set_consent("statistics-anonymous", stats);
    wp_set_consent("marketing", mkt);
    /* Rely on native `wp_listen_for_consent_change` from each `wp_set_consent` only — a batched
     * duplicate dispatch here previously caused Site Kit to fire gtag consent twice (deny overwrite). */
}

/**
 * Read Intastellar consent flags from `window.intaCookieConsents` (set from cookie on load).
 * @returns {{ functional: boolean, statistics: boolean, marketing: boolean } | null} null if no consent object.
 */
function intaWpReadIntastellarConsentBooleansFromWindow() {
    const c = window.intaCookieConsents;
    if (!c || typeof c !== "object") {
        return null;
    }
    return {
        functional: c.functionalCookies === "checked" || c.functionalCookies === true,
        statistics: c.staticsticCookies === "checked" || c.staticsticCookies === true,
        marketing: c.advertisementCookies === "checked" || c.advertisementCookies === true,
    };
}

/**
 * Re-apply WP Consent API cookies from the stored Intastellar cookie (e.g. after reload).
 * On first paint, `gtag('consent','update')` often runs before `wp_set_consent` exists — this runs once WP is ready.
 */
function intaWpTrySyncWpFromStoredIntastellarConsentOnce() {
    if (!intaWpConsentApiActive() || window._intaWpStoredConsentSyncedToWp) {
        return !!window._intaWpStoredConsentSyncedToWp;
    }
    const b = intaWpReadIntastellarConsentBooleansFromWindow();
    if (!b) {
        return false;
    }
    intaWpApplyConsentFromIntastellarChoices(b.functional, b.statistics, b.marketing);
    window._intaWpStoredConsentSyncedToWp = true;
    return true;
}

function intaWpScheduleSyncWpFromStoredIntastellarConsent() {
    if (window._intaWpCookieSyncScheduled) {
        return;
    }
    if (!intaWpReadIntastellarConsentBooleansFromWindow()) {
        return;
    }
    window._intaWpCookieSyncScheduled = true;
    const tick = function () {
        return intaWpTrySyncWpFromStoredIntastellarConsentOnce();
    };
    if (tick()) {
        return;
    }
    if (typeof window !== "undefined" && window.addEventListener) {
        window.addEventListener("DOMContentLoaded", tick);
        window.addEventListener("load", tick);
    }
    let n = 0;
    const id = setInterval(function () {
        if (tick() || ++n >= 80) {
            clearInterval(id);
        }
    }, 100);
}

/**
 * Shopify Customer Privacy: map Intastellar consent values to booleans.
 * Send analytics + marketing + preferences together; omit `sale_of_data` unless CCPA opt-out is stored.
 */
function intaShopifyConsentFlag(v) {
    return v === "checked" || v === true;
}

/**
 * Build Shopify payload from current Intastellar cookie only (not stale window.intaCookieConsents).
 * If IntastellarConsentSolution is missing / invalid → deny all so Shopify does not keep old "yes".
 */
function intaShopifyBuildSetTrackingConsentPayload() {
    let denyAll = { analytics: false, marketing: false, preferences: false };
    try {
        let name = (typeof window !== "undefined" && window.int_hideCookieBannerName) || "IntastellarConsentSolution";
        let raw = typeof getCookie === "function" && name ? getCookie(name) : "";
        if (!raw || String(raw).indexOf("__inta") === -1) {
            return intaShopifyMergePayloadWithCcpaSaleOptOut(denyAll);
        }
        if (typeof decodeIntaConsentsObject !== "function") {
            return intaShopifyMergePayloadWithCcpaSaleOptOut(denyAll);
        }
        let parsed = JSON.parse(decodeIntaConsentsObject(String(raw).split(".")[2]));
        let c = parsed && parsed.consents;
        if (!c || typeof c !== "object") {
            return intaShopifyMergePayloadWithCcpaSaleOptOut(denyAll);
        }
        return intaShopifyMergePayloadWithCcpaSaleOptOut({
            analytics: intaShopifyConsentFlag(c.staticsticCookies),
            marketing: intaShopifyConsentFlag(c.advertisementCookies),
            preferences: intaShopifyConsentFlag(c.functionalCookies),
        });
    } catch (e) {
        return intaShopifyMergePayloadWithCcpaSaleOptOut(denyAll);
    }
}

function intaShopifyPayloadFromConsentsObject(c) {
    let denyAll = { analytics: false, marketing: false, preferences: false };
    if (!c || typeof c !== "object") {
        return intaShopifyMergePayloadWithCcpaSaleOptOut(denyAll);
    }
    return intaShopifyMergePayloadWithCcpaSaleOptOut({
        analytics: intaShopifyConsentFlag(c.staticsticCookies),
        marketing: intaShopifyConsentFlag(c.advertisementCookies),
        preferences: intaShopifyConsentFlag(c.functionalCookies),
    });
}

function intaShopifyApplyTrackingConsentPayload(payload, done) {
    if (!payload || typeof payload !== "object") {
        if (typeof done === "function") {
            done();
        }
        return;
    }
    intaShopifyEnqueueSetTrackingConsent(Object.assign({}, payload), done);
}

function intaShopifySetTrackingConsentFromIntastellar(done) {
    intaShopifyApplyTrackingConsentPayload(intaShopifyBuildSetTrackingConsentPayload(), done);
}

/** When consents come from postMessage before cookie is written, pass the object explicitly. */
function intaShopifySetTrackingConsentFromConsentsObject(consents, done) {
    intaShopifyApplyTrackingConsentPayload(intaShopifyPayloadFromConsentsObject(consents), done);
}

window.intaShopifySetTrackingConsentFromIntastellar = intaShopifySetTrackingConsentFromIntastellar;
window.intaShopifySetTrackingConsentFromConsentsObject = intaShopifySetTrackingConsentFromConsentsObject;

/**
 * Shopify Customer Privacy: *Allowed() methods combine merchant settings, visitor region, and consent.
 * @see https://shopify.dev/docs/api/customer-privacy
 */
function intaShopifyGetProcessingAllowedSnapshot() {
    let api = window.Shopify && window.Shopify.customerPrivacy;
    let snap = {
        preferencesProcessingAllowed: null,
        analyticsProcessingAllowed: null,
        marketingAllowed: null,
        saleOfDataAllowed: null,
        region: null,
        currentVisitorConsent: null,
    };
    if (!api) {
        return snap;
    }
    try {
        if (typeof api.preferencesProcessingAllowed === "function") {
            snap.preferencesProcessingAllowed = !!api.preferencesProcessingAllowed();
        }
        if (typeof api.analyticsProcessingAllowed === "function") {
            snap.analyticsProcessingAllowed = !!api.analyticsProcessingAllowed();
        }
        if (typeof api.marketingAllowed === "function") {
            snap.marketingAllowed = !!api.marketingAllowed();
        }
        if (typeof api.saleOfDataAllowed === "function") {
            snap.saleOfDataAllowed = !!api.saleOfDataAllowed();
        }
        if (typeof api.getRegion === "function") {
            snap.region = api.getRegion();
        }
        if (typeof api.currentVisitorConsent === "function") {
            snap.currentVisitorConsent = api.currentVisitorConsent();
        }
    } catch (e) {
        /* ignore */
    }
    return snap;
}

let intaShopifyVisitorConsentListenerInstalled = false;

function intaShopifyRefreshCustomerPrivacyState(visitorDetail) {
    let allowed = intaShopifyGetProcessingAllowedSnapshot();
    window.__intaShopifyCustomerPrivacy = {
        allowed: allowed,
        lastVisitorConsentEventDetail: visitorDetail != null ? visitorDetail : null,
        updatedAt: new Date().toISOString(),
    };
    if (window.dataLayer && Array.isArray(window.dataLayer)) {
        try {
            window.dataLayer.push({
                event: "inta_shopify_customer_privacy_updated",
                intaShopifyAllowed: {
                    preferencesProcessingAllowed: allowed.preferencesProcessingAllowed,
                    analyticsProcessingAllowed: allowed.analyticsProcessingAllowed,
                    marketingAllowed: allowed.marketingAllowed,
                    saleOfDataAllowed: allowed.saleOfDataAllowed,
                },
                intaShopifyVisitorDetail: visitorDetail != null ? visitorDetail : undefined,
            });
        } catch (e) {
            /* ignore */
        }
    }
}

function intaShopifyOnVisitorConsentCollected(ev) {
    intaShopifyRefreshCustomerPrivacyState(ev && ev.detail);
}

function intaShopifyInstallCustomerPrivacyListeners() {
    if (intaShopifyVisitorConsentListenerInstalled) {
        return;
    }
    intaShopifyVisitorConsentListenerInstalled = true;
    document.addEventListener("visitorConsentCollected", intaShopifyOnVisitorConsentCollected, false);
}

window.intaShopifyGetProcessingAllowedSnapshot = intaShopifyGetProcessingAllowedSnapshot;
window.intaShopifyRefreshCustomerPrivacyState = intaShopifyRefreshCustomerPrivacyState;

// --- Helper function to detect Vendors of Cookies (lazy-loaded; stub until uc-vendors loads) ---
function detectCookieVendor(cookie) {
    if (typeof window.__intaDetectCookieVendor === 'function') {
        return window.__intaDetectCookieVendor(cookie);
    }
    return 'unknown vendor';
}

// --- Helper: Map cookie name to consent type (populated when uc-vendors loads) ---
var COOKIE_CONSENT_TYPE_MAP = null;

// Load uc-vendors.js on DOMContentLoaded to reduce initial parse/execute (detectCookieVendor + map ~15KB)
function loadUcVendors() {
    if (window.__intaDetectCookieVendor) return;
    var base = (typeof window.INTA !== 'undefined' && window.INTA.settings && window.INTA.settings.vendorsUrl) || 'https://consents.cdn.intastellarsolutions.com/uc-vendors.js';
    var s = document.createElement('script');
    s.src = base;
    s.async = true;
    intaAppendToDocumentHead(s);
    s.onload = function () {
        COOKIE_CONSENT_TYPE_MAP = window.__intaCookieConsentTypeMap || null;
    };
}

function getConsentTypeForCookie(cookieName) {
    // Delegate to uc-vendors when loaded
    if (typeof window.__intaGetConsentTypeForCookie === 'function') {
        return window.__intaGetConsentTypeForCookie(cookieName);
    }
    // Fallback until uc-vendors loads
    if (COOKIE_CONSENT_TYPE_MAP && COOKIE_CONSENT_TYPE_MAP[cookieName]) return COOKIE_CONSENT_TYPE_MAP[cookieName];
    if (COOKIE_CONSENT_TYPE_MAP) {
        for (let key in COOKIE_CONSENT_TYPE_MAP) {
            if (cookieName.startsWith(key)) return COOKIE_CONSENT_TYPE_MAP[key];
        }
    }
    return 'marketing';
}

// --- Blocked iframe / embed consent copy (lazy-loaded uc-blocked-iframe.js) ---
var __intaBlockedIframeLoadStarted = false;

function loadUcBlockedIframeMessages() {
    if (window.__intaBlockedIframeContentMessage) {
        return;
    }
    if (__intaBlockedIframeLoadStarted) {
        return;
    }
    __intaBlockedIframeLoadStarted = true;
    var base = (typeof window.INTA !== "undefined" && window.INTA.settings && window.INTA.settings.blockedIframeUrl)
        || "https://consents.cdn.intastellarsolutions.com/uc-blocked-iframe.js";
    if (typeof intastellarDevMode !== "undefined" && intastellarDevMode) {
        base = "../../dev/uc-blocked-iframe.dev.js";
    }
    var s = document.createElement("script");
    s.src = base;
    s.async = true;
    intaAppendToDocumentHead(s);
}

function intaEnsureBlockedIframeMessagesLoaded() {
    loadUcBlockedIframeMessages();
}

function intaResolveBlockedIframeLocaleKey() {
    if (typeof window.__intaResolveBlockedIframeLocaleKey === "function") {
        return window.__intaResolveBlockedIframeLocaleKey();
    }
    return "english";
}

function intaBlockedIframeContentMessage(domain, localeKey) {
    if (typeof window.__intaBlockedIframeContentMessage === "function") {
        return window.__intaBlockedIframeContentMessage(domain, localeKey);
    }
    return "<p>This content is provided by " + domain + ".</p>";
}

function intaBlockedIframeButtonText(scriptType, localeKey) {
    if (typeof window.__intaBlockedIframeButtonText === "function") {
        return window.__intaBlockedIframeButtonText(scriptType, localeKey);
    }
    return "Accept cookies";
}

function intaNormalizeBlockedIframeDomain(domain, node, cookieList) {
    if (node && node.classList && node.classList.contains("trustpilot-widget")) {
        domain = "www.trustpilot.com";
    }
    var list = cookieList || (typeof inta_marketingCookieList !== "undefined" ? inta_marketingCookieList : []);
    list.forEach(function (cookie) {
        var i = 0, d = domain, p = d.split(".");
        d = p.slice(-1 - ++i).join(".");
        domain = d;
        if (cookie && cookie.domains && cookie.domains.indexOf(domain) > -1) {
            domain = cookie.vendor;
        }
    });
    return domain;
}

function intaPickBlockedIframeStrings(domain, node, scriptType, cookieList) {
    intaEnsureBlockedIframeMessagesLoaded();
    var localeKey = intaResolveBlockedIframeLocaleKey();
    var normalized = intaNormalizeBlockedIframeDomain(domain, node, cookieList);
    return {
        textLanguage: intaBlockedIframeContentMessage(normalized, localeKey),
        btnText: intaBlockedIframeButtonText(scriptType, localeKey)
    };
}

// --- Start Cookie Interception ---
(function () {
    let desc = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie');
    Object.defineProperty(document, 'cookie', {
        configurable: true,
        enumerable: true,
        get: function () {
            return desc.get.call(this);
        },
        set: function (cookieString) {
            window.INTA.observedCookieSource = 'cookie';
            try {
                let cookieName = cookieString.split('=')[0].trim();
                let rawValue = cookieString.split('=')[1]?.split(';')[0];
                let cookieDomain = cookieString.split(';').find(part => part.trim().toLowerCase().startsWith('domain='))?.split('=')[1]?.trim() || window.location.hostname;
                // Use cookie name to determine consent type
                let consentType = getConsentTypeForCookie(cookieName);
                recordCookie({
                    name: cookieName,
                    source: window.INTA.observedCookieSource || 'unknown',
                    observedAt: Date.now(),
                    path: window.location.pathname,
                    domain: window.location.hostname,
                    cookieDomain,
                    rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
                    hadValuePreConsent: typeof rawValue === 'string' && rawValue.length > 0,
                    consentGiven: hasConsent(consentType),
                    vendor: detectCookieVendor({ name: cookieName, value: rawValue })
                })
            } catch (e) { /* ignore */ }
            return desc.set.call(this, cookieString);
        }
    });
})();

// --- CookieStorage Observer ---
if ("cookieStore" in window) {
    cookieStore.addEventListener("change", (event) => {
        event.changed.forEach(cookie => {
            window.INTA.observedCookieSource = 'cookieStore';
            let consentType = getConsentTypeForCookie(cookie.name);
            recordCookie({
                name: cookie.name,
                source: 'cookieStore',
                observedAt: Date.now(),
                path: cookie.path || window.location.pathname,
                domain: cookie.domain || window.location.hostname,
                cookieDomain: cookie.domain || window.location.hostname,
                rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
                hadValuePreConsent: 0,
                consentGiven: hasConsent(consentType),
                vendor: detectCookieVendor({ name: cookie.name, value: cookie.value })
            })
        })
    });
}

// --- Start localStorage Interception ---
(function () {
    let originalSetItem = localStorage.setItem;
    localStorage.setItem = function (key, value) {
        window.INTA.observedCookieSource = 'localStorage';
        let consentType = getConsentTypeForCookie(key);
        recordCookie({
            name: key,
            source: 'localStorage',
            observedAt: Date.now(),
            path: window.location.pathname,
            domain: window.location.hostname,
            rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
            hadValuePreConsent: typeof value === 'string' && value.length > 0,
            consentGiven: hasConsent(consentType),
            vendor: detectCookieVendor({ name: key, value: value })
        });
        return originalSetItem.apply(this, arguments);
    };
})();

// --- Start memory Interception (example) ---
window.INTA.memorySet = function (key, value) {
    window.INTA.observedCookieSource = 'memory';
    let consentType = getConsentTypeForCookie(key);
    recordCookie({
        name: key,
        value: value,
        source: 'memory',
        observedAt: Date.now(),
        path: window.location.pathname,
        domain: window.location.hostname,
        rootDomain: window.INTA?.settings?.rootDomain || window.location.hostname,
        hadValuePreConsent: typeof value === 'string' && value.length > 0,
        consentGiven: hasConsent(consentType),
        vendor: detectCookieVendor({ name: key, value: value })
    });
    window.INTA._memory = window.INTA._memory || {};
    window.INTA._memory[key] = value;
};

function IntastellarSnapShot(stage) {

}

// Example usage:
// let rootDomain = "group1.com";
// let partnerDomains = ["domain-a.com", "domain-b.com"];
// requestConsentState('user-123', rootDomain, partnerDomains);
// setConsentState('user-123', { marketing: true, statistics: false, functional: true }, rootDomain, partnerDomains);
// --- End Cross-site Consent Tracking ---

/* - - - Setup - - - */

let intaCookiePref = "IntastellarConsentSolution";
let int_hideCookieBannerName = window.int_hideCookieBannerName = intaCookiePref;
let int_FunctionalCookies = intaCookiePref + ":Functional-cookies";
let int_marketingCookies = intaCookiePref + ":Advertisment-cookies";
let int_staticsticCookies = intaCookiePref + ":Statistics-cookies";
let int_visitorCheck = intaCookiePref + "visitorCheck";
let button__acceptAll = document.querySelector(".intastellarCookieBanner__acceptAll");
let button__acceptAllNecessary = document.querySelector(".intastellarCookieBanner__acceptNecessary");
let intastellarShowHideDetailsText = "Show details";
let adsbygoogle = window.adsbygoogle || [];
let intastellarCookieBannerRootDomain = "https://consents.cdn.intastellarsolutions.com";
let intastellarAssetsCDNdomain = "https://www.intastellar-consents.com";
let intaCookieConsents = window.intaCookieConsents = (getCookie(int_hideCookieBannerName)) ? JSON.parse(decodeIntaConsentsObject(getCookie(int_hideCookieBannerName)?.split(".")[2]))?.consents : null;
window.uetq = window.uetq || [];
// On page load, update VWO consent if consent object exists
if (intaCookieConsents) {
    updateVwoConsent(intaCookieConsents);
}
let intaCookieConsentsUserId = (getCookie(int_hideCookieBannerName)) ? JSON.parse(decodeIntaConsentsObject(getCookie(int_hideCookieBannerName)?.split(".")[2]))?.uid : null;

/** Intastellar script URL when `document.currentScript` is null (Remix, Vite, Webpack, ES modules). */
function intaGuessIntastellarScriptSrc() {
    try {
        if (document.currentScript && document.currentScript.src) {
            return document.currentScript.src;
        }
    } catch (e) {
        /* ignore */
    }
    const scripts = document.getElementsByTagName("script");
    for (let i = scripts.length - 1; i >= 0; i--) {
        const s = scripts[i];
        const src = s && s.src;
        if (!src) {
            continue;
        }
        if (/uc\.js|\/uc\.js|consents\.cdn|intastellar-consents|gdpr\.dev|\/cb\.js|\/cb\.dev|floating\.js/i.test(src)) {
            return src;
        }
    }
    return "";
}

function findScriptParameter(value) {
    const currentURL = intaGuessIntastellarScriptSrc();
    if (!currentURL || currentURL.indexOf(value) === -1) {
        return undefined;
    }
    try {
        const url = new URL(currentURL, window.location.href);
        return url.searchParams.get(value);
    } catch (e) {
        return undefined;
    }
}

let isGtmMode = findScriptParameter("ref") === "gtm";
let isWordPress = document.getElementById('intastellar-gdpr-settings-js') !== null;
let FunctionalCheckbox = document.querySelector("#functional");
let StaticsCheckBox = document.querySelector("#statics");
let MarketingCheckBox = document.querySelector("#marketing");
let pluginSource = findScriptParameter("utm_source") === undefined ? "Intastellar+Solutions+Cookiebanner" : findScriptParameter("utm_source");
window.platform = findScriptParameter("utm_source") === undefined ? "Manual" : findScriptParameter("utm_source");
let poweredBy = "";
window.dataLayer = window.dataLayer || [];
intaWpInstallDataLayerConsentMirror();
let intaConsentsObjectVariable = {
    consents: {
        staticsticCookies: false,
        functionalCookies: false,
        advertisementCookies: false,
    },
    time: new Date().toGMTString(),
    uid: Math.random().toString(16).slice(2),
    domain: window?.INTA?.settings?.rootDomain || window.location.host,
    sharingDomains: [],
    tcString: null,
}

window._paq = window._paq || [];
_paq.push(['requireConsent']);


window.clarity && window.clarity('consentv2', {
    ad_Storage: "denied",
    analytics_Storage: "denied"
});

window.uetq.push('consent', 'default', {
    'ad_storage': 'denied'
});



window.disableHubSpotCookieBanner = true;
var _hsp = (window._hsp = window._hsp || []);

function gtag() {
    dataLayer.push(arguments);
}


if (window._intaConsentInitialized) {
    console.log('Intastellar consent already initialized, skipping...');
}

window._intaConsentInitialized = true;

intaWpEnsureConsentTypeOptinAnnouncedOnce();

if (!isGtmMode && !window._gtagDefaultFired && typeof gtag === 'function') {
    // Only set defaults if GTM hasn't already done so
    if (!window.google_tag_manager || !window.google_tag_manager['consent_default_set']) {
        // Strict opt-in regions (GDPR-style). ISO 3166: 'CA' = Canada, not California.
        // California is handled separately below via region ['US-CA'] (CCPA / opt-out style).
        gtag('consent', 'default', {
            "ad_storage": 'denied',
            "personalization_storage": 'denied',
            "analytics_storage": 'denied',
            "functionality_storage": 'denied',
            "ads_data_redaction": 'granted',
            "ad_user_data": 'denied',
            "ad_personalization": 'denied',
            "security_storage": 'granted',
            "url_passthrough": true,
            "wait_for_update": 500,
            "region": ['EU', 'UK', 'CH', 'NO', 'IS', 'LI', 'CA', 'BR', 'ZA', 'TR', 'AR', 'IL', 'TH']
        });
        /* console.log("Intastellar Consents: Applied STRICT defaults (EU/UK/CA/BR/etc.)"); */

        // California only: CCPA-style defaults (region US-CA). Rest of US uses global baseline below.
        gtag('consent', 'default', {
            "ad_storage": 'granted',
            "personalization_storage": 'granted',
            "analytics_storage": 'granted',
            "functionality_storage": 'granted',
            "ads_data_redaction": 'denied',
            "ad_user_data": 'granted',
            "ad_personalization": 'granted',
            "security_storage": 'granted',
            "url_passthrough": true,
            "wait_for_update": 500,
            "region": ['US-CA']
        });
        /* console.log("Intastellar Consents: Applied CALIFORNIA defaults (US-CA)"); */

        // Global baseline: strict (denied) for every region not matched above.
        // Regional rows above take precedence (strict list + TH, etc., and US-CA opt-out style).
        // No separate "rest of world granted" row — that would opt non-listed countries in by default.
        gtag('consent', 'default', {
            'ad_storage': 'denied',
            'personalization_storage': 'denied',
            'analytics_storage': 'denied',
            'functionality_storage': 'denied',
            'ads_data_redaction': 'denied',
            'ad_user_data': 'denied',
            'ad_personalization': 'denied',
            'security_storage': 'granted',
            'url_passthrough': true,
            'wait_for_update': 500,
        });
        window._gtagDefaultFired = true;
    }
} else if (isGtmMode) { }

if (typeof fbq === "undefined" || typeof fbq === "null") {
    function fbq() { }
}

if (hasConsent("advertisement")) {
    gtag('consent', 'update', {
        'personalization_storage': 'granted',
        'ads_data_redaction': 'granted',
        'ad_storage': 'granted',
        'ad_user_data': 'granted',
        'ad_personalization': 'granted',
        'url_passthrough': true,
    });

    // Pintrk
    if (typeof pintrk === 'function') {
        try {
            pintrk('setconsent', true);
        } catch (e) { /* ignore */ }
    }

    window.uetq.push('consent', 'update', {
        'ad_storage': 'granted'
    });

    window.clarity && window.clarity('consentv2', {
        ad_Storage: "granted",
        analytics_Storage: "denied"
    });

    fbq('consent', 'grant');
    // Enable ads
    (adsbygoogle = window.adsbygoogle || []).pauseAdRequests = 0;
    (adsbygoogle = window.adsbygoogle || []).requestNonPersonalizedAds = 0;

}

if (hasConsent("analytics")) {
    gtag('consent', 'update', {
        'analytics_storage': 'granted',
        'url_passthrough': true,
    })
    window.clarity && window.clarity('consentv2', {
        ad_Storage: "denied",
        analytics_Storage: "granted"
    });
    window.uetq.push('consent', 'update', {
        'analytics_storage': 'granted'
    });
    
    _paq.push(['setConsentGiven']);
}

if (hasConsent("functional")) {
    gtag('consent', 'update', {
        'functionality_storage': 'granted',
    })
    window.uetq.push('consent', 'update', {
        'functionality_storage': 'granted'
    });

}

intaWpScheduleSyncWpFromStoredIntastellarConsent();

/* _hsp.push(['doNotTrack']);
_hsp.push(['revokeCookieConsent']); */
window._hsp.push([
    'setHubSpotCookieConsent',
    {
        'analytics': intaCookieConsents?.staticsticCookies === "checked",
        'advertisement': intaCookieConsents?.advertisementCookies === "checked",
        'functional': intaCookieConsents?.functionalCookies === "checked",
    }
]);

window.Shopify = window.Shopify || {};
window.Shopify.customerPrivacy = window.Shopify.customerPrivacy || {};
// Hide Shopify’s own banner when using Intastellar; real API methods come from loadFeatures below.
window.Shopify.customerPrivacy.shouldShowBanner = function () { return false; };

intaShopifyInstallCustomerPrivacyListeners();

// BUGFIX: was `window.Shopify ?? loadFeatures(...)` — after assigning `window.Shopify = {}` above,
// Shopify is always truthy so `??` never ran loadFeatures and customerPrivacy stayed a stub.
let intaShopifyConsentApiLoadStarted = false;
function intaShopifyLoadConsentTrackingApi() {
    if (intaShopifyConsentApiLoadStarted) {
        return true;
    }
    if (typeof window.Shopify.loadFeatures !== 'function') {
        return false;
    }
    intaShopifyConsentApiLoadStarted = true;
    window.Shopify.loadFeatures(
        [
            {
                name: 'consent-tracking-api',
                version: '0.1',
            },
        ],
        (error) => {
            if (error) {
                console.error("Shopify consent tracking API error:", error);
                return;
            }
            // Sync Intastellar cookie → Shopify (done callback refreshes *Allowed snapshot via intaShopifyApplyTrackingConsentPayload)
            intaShopifySetTrackingConsentFromIntastellar(() => console.log("Shopify Customer Privacy synced from Intastellar"));
            // consent-tracking-api may replace customerPrivacy; keep Shopify’s banner off while Intastellar runs
            window.Shopify.customerPrivacy.shouldShowBanner = function () {
                return false;
            };
        },
    );
    return true;
}

if (!intaShopifyLoadConsentTrackingApi()) {
    // Shopify core (loadFeatures) often loads after this script — retry briefly on storefronts
    let intaShopifyRetries = 0;
    let intaShopifyRetryId = setInterval(() => {
        if (intaShopifyLoadConsentTrackingApi() || ++intaShopifyRetries > 50) {
            clearInterval(intaShopifyRetryId);
        }
    }, 100);
}

function optOutCCPA() {
    // Google Tag Manager / gtag
    gtag('consent', 'update', {
        'ad_storage': 'denied',
        'ad_user_data': 'denied',
        'ad_personalization': 'denied'
    });

    // Microsoft Clarity
    if (window.clarity) {
        try {
            window.clarity('consent', 'denied');
            // For Clarity V2, if used:
            window.clarity('consentv2', {
                ad_Storage: "denied",
                analytics_Storage: "denied"
            });
        } catch (e) { /* ignore */ }
    }

    // Matomo
    if (window._paq) {
        try {
            window._paq.push(['requireConsent']);
            window._paq.push(['forgetUserOptOut']);
        } catch (e) { /* ignore */ }
    }

    // Pintrk
    if (typeof pintrk === 'function') {
        try {
            pintrk('setconsent', false);
        } catch (e) { /* ignore */ }
    }

    // Microsoft UET
    if (window.uetq) {
        try {
            window.uetq.push('consent', 'update', { 'ad_storage': 'denied' });
        } catch (e) { /* ignore */ }
    }

    // HubSpot
    if (window._hsp) {
        try {
            window._hsp.push(['setHubSpotCookieConsent', {
                analytics: false,
                advertisement: false,
                functional: false
            }]);
        } catch (e) { /* ignore */ }
    }

    // Shopify: data sale/sharing opt-out only — does not change analytics/marketing/preferences (Shopify docs).
    try {
        localStorage.setItem("ccpa_opt_out", "true");
        intaShopifySetTrackingConsentSafe({ sale_of_data: false }, function () {
            console.log("Shopify CCPA opt-out set");
        });
    } catch (e) { /* ignore */ }

    alert("Your opt-out has been saved. We won’t sell or share your personal information.");
}

// --- Server-Side Tagging & Interception Implementation ---
// Helper: Determine consent type for a given URL using allScripts regex
function getConsentTypeForUrl(url) {
    if (!url) return 'marketing';
    let compiled = intaGetCompiledScriptPatterns();
    for (let i = 0; i < compiled.length; i++) {
        let scriptType = compiled[i].type;
        let regexes = compiled[i].regexes;
        for (let j = 0; j < regexes.length; j++) {
            try {
                if (regexes[j].test(url)) {
                    if (scriptType === 'statics') return 'statistics';
                    return scriptType;
                }
            } catch (e) { /* ignore */ }
        }
    }
    // Default fallback
    return 'marketing';
}

/**
 * Machine-readable IAB device-storage disclosures and GVL-listed vendor URLs.
 * cb.js sets `intaIsGvlVendorPassThroughUrl` / `__intaGvlPassThroughUrls` after vendors load; this also matches
 * common disclosure JSON paths so XHR is not blocked before the GVL finishes loading.
 */
function intaIsGvlPassThroughRequest(url) {
    if (!url || typeof url !== "string") {
        return false;
    }
    if (typeof window.intaIsGvlVendorPassThroughUrl === "function") {
        try {
            if (window.intaIsGvlVendorPassThroughUrl(url)) {
                return true;
            }
        } catch (eFn) { /* ignore */ }
    }
    let u = url.trim();
    let list = window.__intaGvlPassThroughUrls;
    if (Array.isArray(list) && list.indexOf(u) !== -1) {
        return true;
    }
    try {
        let parsed = new URL(u, window.location.origin);
        let hosts = window.__intaGvlPassThroughHosts;
        if (Array.isArray(hosts) && hosts.indexOf(parsed.hostname) !== -1) {
            return true;
        }
        let p = (parsed.pathname || "").toLowerCase();
        if (parsed.protocol === "https:" && p.endsWith(".json") && /devicestorage|device_storage|compliance_devicestorage/.test(p)) {
            return true;
        }
    } catch (e0) { /* ignore */ }
    return false;
}

// Helper: Send intercepted data to backend for storage/categorization
async function sendToBackend(data) {
    try {
        let base = (typeof window.INTA?.settings?.backendUrl === 'string') ? window.INTA.settings.backendUrl : 'https://consents.cdn.intastellarsolutions.com/tests/backend/test.php';
        await fetch(base, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });
    } catch (e) {
        console.log(e);
    }
    return;
}

// Helper: Server-side tagging - send GA4 events via backend (consent-aware)
// Server checks consents: accepted = full data (user_id, IP, etc); not accepted = minimal
window.sendEventToServerSideTagging = function (eventName, params, opts) {
    let measurementId = (opts && opts.measurement_id) || (window.INTA && window.INTA.settings && window.INTA.settings.gtagId) || '';
    if (!measurementId || !/^G-[A-Z0-9]+$/i.test(measurementId)) return;
    let consents = window.intaCookieConsents || {};
    var consentAcceptedAt = null;
    try {
        if (typeof getCookie === 'function' && typeof decodeIntaConsentsObject === 'function' && typeof int_hideCookieBannerName !== 'undefined') {
            var c = getCookie(int_hideCookieBannerName);
            if (c && c.indexOf && c.indexOf('__inta') > -1) {
                var parts = c.split('.');
                var decoded = parts[2] ? JSON.parse(decodeIntaConsentsObject(parts[2]) || '{}') : {};
                consentAcceptedAt = decoded.time || null;
            }
        }
    } catch (e) { }
    let uid = (window.intaConsentsObjectVariable && window.intaConsentsObjectVariable.uid) || '';
    let base = (typeof window.INTA !== 'undefined' && typeof window.INTA.settings?.backendUrl === 'string') ? window.INTA.settings.backendUrl : 'https://consents.cdn.intastellarsolutions.com/tests/backend/test.php';
    fetch(base, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            action: 'ga4_event',
            measurement_id: measurementId,
            consents: consents,
            consent_accepted_at: consentAcceptedAt,
            client_id: (opts && opts.client_id) || ('cid_' + Date.now().toString(36) + Math.random().toString(36).slice(2)),
            user_id: (opts && opts.user_id) || uid,
            session_id: (opts && opts.session_id) || ('sess_' + Date.now()),
            page_location: (opts && opts.page_location) || window.location.href,
            page_title: (opts && opts.page_title) || (document.title || ''),
            events: [{ name: eventName || 'page_view', params: params || {} }]
        })
    }).catch(function () { });
};

// IAB TC String generator
(function (window) {
    // Minimal IAB TCF encoder for browser use
    function padBits(num, len) {
        let s = num.toString(2);
        return "0".repeat(len - s.length) + s;
    }
    function strToBits(str) {
        // 2 chars, each 6 bits (A=0, Z=25, a=26, z=51)
        return padBits(str.charCodeAt(0) - 65, 6) + padBits(str.charCodeAt(1) - 65, 6);
    }
    function base64UrlEncode(bytes) {
        let binary = '';
        for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
        return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    }
    function base64UrlDecode(str) {
        str = (str || '').replace(/-/g, '+').replace(/_/g, '/');
        while (str.length % 4) str += '=';
        var binary = atob(str);
        var out = '';
        for (var i = 0; i < binary.length; i++) out += String.fromCharCode(binary.charCodeAt(i));
        return out;
    }

    // Minimal TCModel
    function TCModel() {
        this.purposeConsents = [];
        this.vendorConsents = [];
        this.vendorLegitimateInterests = [];
        this.disclosedVendors = []; // TCF 2.3: vendors disclosed to user in CMP
    }

    /** TCF 2.3: Encode Disclosed Vendors segment (segment type 1). */
    function encodeDisclosedVendorsSegment(maxVendorId, disclosed) {
        if (maxVendorId <= 0) return '';
        let bits = '';
        bits += padBits(1, 3);   // segment type 1 = vendorsDisclosed
        bits += padBits(maxVendorId, 16);
        for (let i = 0; i < maxVendorId; i++) bits += (disclosed && disclosed[i]) ? '1' : '0';
        let bytes = [];
        for (let i = 0; i < bits.length; i += 8) bytes.push(parseInt(bits.substr(i, 8).padEnd(8, '0'), 2));
        return base64UrlEncode(bytes);
    }

    // Minimal TCString encoder
    var TCString = {
        encode: function (tcModel) {
            // Support all vendors (not just first 24)
            let bits = "";
            bits += padBits(2, 6); // Version
            let now = Math.floor(Date.now() / 100); // 0.1s increments
            bits += padBits(now, 36); // Created
            bits += padBits(now, 36); // LastUpdated
            bits += padBits(1, 12); // CmpId
            bits += padBits(1, 12); // CmpVersion
            bits += padBits(0, 6); // ConsentScreen
            bits += strToBits("EN"); // ConsentLanguage
            bits += padBits(1, 12); // VendorListVersion
            bits += padBits(3, 6); // TCFPolicyVersion 3 = TCF 2.3
            bits += padBits(0, 1); // IsServiceSpecific
            bits += padBits(0, 1); // UseNonStandardStacks
            bits += padBits(0, 12); // SpecialFeatureOptIns
            // PurposeConsents (24 bits)
            for (let i = 0; i < 24; i++) bits += tcModel.purposeConsents && tcModel.purposeConsents[i] ? "1" : "0";
            // PurposeLegitInterests (24 bits, all 0)
            bits += "0".repeat(24);
            bits += padBits(0, 1); // PurposeOneTreatment
            bits += strToBits("EN"); // PublisherCC
            // VendorConsents (maxVendorId, 16 bits for maxVendorId, then maxVendorId bits for consents)
            let maxVendorId = (tcModel.vendorConsents && tcModel.vendorConsents.length) || 0;
            bits += padBits(maxVendorId, 16);
            for (let i = 0; i < maxVendorId; i++) bits += tcModel.vendorConsents && tcModel.vendorConsents[i] ? "1" : "0";
            // Convert bits to bytes
            let bytes = [];
            for (let i = 0; i < bits.length; i += 8) {
                bytes.push(parseInt(bits.substr(i, 8).padEnd(8, "0"), 2));
            }
            let coreString = base64UrlEncode(bytes);
            // TCF 2.3: mandatory Disclosed Vendors segment (required for new/updated signals from Feb 28, 2026)
            let disclosed = (tcModel.disclosedVendors && tcModel.disclosedVendors.length >= maxVendorId)
                ? tcModel.disclosedVendors.slice(0, maxVendorId)
                : (tcModel.vendorConsents || []).slice(0, maxVendorId).map(function () { return true; });
            let disclosedSegment = encodeDisclosedVendorsSegment(maxVendorId, disclosed);
            return disclosedSegment ? coreString + "." + disclosedSegment : coreString;
        },
        decode: function (tcString) {
            let coreOnly = (tcString || '').split('.')[0];
            let binary = base64UrlDecode(coreOnly);
            let bits = '';
            for (let i = 0; i < binary.length; i++) {
                bits += ('00000000' + binary.charCodeAt(i).toString(2)).slice(-8);
            }
            // Parse fields (see encoder for bit lengths)
            let offset = 0;
            function read(len) {
                let val = bits.substr(offset, len);
                offset += len;
                return val;
            }
            let version = parseInt(read(6), 2);
            let created = parseInt(read(36), 2);
            let lastUpdated = parseInt(read(36), 2);
            let cmpId = parseInt(read(12), 2);
            let cmpVersion = parseInt(read(12), 2);
            let consentScreen = parseInt(read(6), 2);
            let consentLanguage = String.fromCharCode(parseInt(read(6), 2) + 65, parseInt(read(6), 2) + 65);
            let vendorListVersion = parseInt(read(12), 2);
            let tcfPolicyVersion = parseInt(read(6), 2);
            let isServiceSpecific = !!parseInt(read(1), 2);
            let useNonStandardStacks = !!parseInt(read(1), 2);
            let specialFeatureOptIns = read(12);
            let purposes = read(24).split('').map(b => b === '1');
            let purposeLegitInterests = read(24);
            let purposeOneTreatment = !!parseInt(read(1), 2);
            let publisherCC = String.fromCharCode(parseInt(read(6), 2) + 65, parseInt(read(6), 2) + 65);
            let maxVendorId = parseInt(read(16), 2);
            let vendorBits = maxVendorId > 0 ? read(maxVendorId) : '';
            let vendors = vendorBits.split('').map(b => b === '1');
            return {
                version,
                created,
                lastUpdated,
                cmpId,
                cmpVersion,
                consentScreen,
                consentLanguage,
                vendorListVersion,
                tcfPolicyVersion,
                isServiceSpecific,
                useNonStandardStacks,
                specialFeatureOptIns,
                purposes,
                maxVendorId,
                vendors
            };
        }
    };

    window.IABTCF = {
        TCModel: TCModel,
        TCString: TCString
    };
})(window);

// Consent check helper
function hasConsent(type) {
    // type: 'functional', 'statistics', 'marketing'
    if (!window.intaCookieConsents) return false;
    if (type === 'functional') return window.intaCookieConsents.functionalCookies === 'checked';
    if (type === 'statistics' || type === 'analytics') return window.intaCookieConsents.staticsticCookies === 'checked';
    if (type === 'advertisement' || type === 'marketing') return window.intaCookieConsents.advertisementCookies === 'checked';
    return false;
}

let ALLOWLIST = [
    location.origin,
    "https://intastellar.app",
    "https://www.intastellarsolutions.com",
    "https://analytics.intastellarsolutions.com",
    "https://api.intastellarsolutions.com",
    "https://apis.intastellarsolutions.com",
    "https://apis.intastellaraccounts.com",
    "https://consents.intastellarsolutions.com",
    "https://vendor-list.consensu.org",
    "/dev/gvl-local.json",
    "https://forms.hsforms.com",
    "https://js.hs-scripts.com",
    "https://js.hsforms.net",
    "https://api.hsforms.com",
    "https://forms.hubspot.com",
    "https://track.hubspot.com",
    "https://js.usemessages.com",
    "https://cdn2.hubspot.net",
    "https://cdn.hsforms.net",
    "https://cdn.weglot.com",
    "https://dev.visualwebsiteoptimizer.com",
    "https://www.google-analytics.com",
    "https://region1.google-analytics.com"
];

function intaNormalizeHostname(host) {
    if (!host) {
        return "";
    }
    return String(host).split(":")[0].replace(/^www\./i, "").toLowerCase();
}

/** Best-effort registrable domain when `INTA.settings.rootDomain` is not set (e.g. `booking.example.com` → `example.com`). */
function intaDeriveSiteRootFromHostname(hostname) {
    let h = intaNormalizeHostname(hostname);
    if (!h) {
        return "";
    }
    let parts = h.split(".");
    if (parts.length <= 2) {
        return h;
    }
    return parts.slice(-2).join(".");
}

function intaGetSiteRootCandidates(pageHostname) {
    let roots = [];
    let configured = window.INTA && window.INTA.settings && window.INTA.settings.rootDomain;
    if (configured) {
        roots.push(intaNormalizeHostname(String(configured)));
    }
    let derived = intaDeriveSiteRootFromHostname(pageHostname);
    if (derived) {
        roots.push(derived);
    }
    let partners = window.INTA && window.INTA.settings && window.INTA.settings.partnerDomain;
    if (Array.isArray(partners)) {
        partners.forEach(function (d) {
            if (d) {
                roots.push(intaNormalizeHostname(String(d)));
            }
        });
    }
    return roots.filter(function (r, i, arr) {
        return r && arr.indexOf(r) === i;
    });
}

function intaIsHostUnderSiteRoot(host, root) {
    let h = intaNormalizeHostname(host);
    let r = intaNormalizeHostname(root);
    if (!h || !r) {
        return false;
    }
    return h === r || h.endsWith("." + r);
}

/** True when target and page share the same configured/derived root (root ↔ subdomain in either direction). */
function intaIsSameSiteHost(targetHostname, pageHostname) {
    let t = intaNormalizeHostname(targetHostname);
    let p = intaNormalizeHostname(pageHostname);
    if (!t || !p) {
        return false;
    }
    if (t === p) {
        return true;
    }
    let roots = intaGetSiteRootCandidates(p);
    for (let i = 0; i < roots.length; i++) {
        if (intaIsHostUnderSiteRoot(t, roots[i]) && intaIsHostUnderSiteRoot(p, roots[i])) {
            return true;
        }
    }
    return false;
}

function isAllowed(url) {
    try {
        let parsedUrl = new URL(url, window.location.origin);
        // Allow all requests to the same origin
        if (parsedUrl.origin === window.location.origin) return true;

        if (
            /(?:\.hubspot\.com|\.hsforms\.com|\.hs-scripts\.com|\.hsforms\.net|\.usemessages\.com|\.cdn2\.hubspot\.net|\.cdn\.hsforms\.net)$/i.test(parsedUrl.hostname)
        ) {
            return true;
        }

        // Allow if matches any allowlist origin
        if (ALLOWLIST.some(domain => parsedUrl.origin === domain)) return true;

        // Root domain ↔ subdomain (either direction), e.g. booking.asasoftware.aero → asasoftware.aero/collect
        if (intaIsSameSiteHost(parsedUrl.hostname, window.location.hostname)) {
            return true;
        }

        // Optionally allow other trusted domains here
        return false;
    } catch (e) {
        return false;
    }
}


// Intercept fetch with consent check
let originalFetch = window.fetch;
window.fetch = function (resource, config) {
    let url = (typeof resource === 'string') ? resource : resource.url;
    // Prevent recursion for backend endpoint
    if (isAllowed(url)) {
        return originalFetch.apply(this, arguments);
    }
    if (intaIsGvlPassThroughRequest(url)) {
        return originalFetch.apply(this, arguments);
    }
    let isExternal = !url.startsWith(window.location.origin);
    if (isExternal) {
        let consentType = getConsentTypeForUrl(url);
        if (!hasConsent(consentType)) {
            if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                console.log('[GDPR] Blocked fetch:', url, 'type:', consentType);
            }
            // Silently block: return a resolved Promise with undefined
            return Promise.resolve(undefined);
        }
    }
    return originalFetch.apply(this, arguments);
};

// Intercept XMLHttpRequest with consent check
let OriginalXHR = window.XMLHttpRequest;
function CustomXHR() {
    let xhr = new OriginalXHR();
    let open = xhr.open;
    xhr.open = function (method, url, ...args) {
        if (isAllowed(url)) {
            return open.apply(this, arguments);
        }
        if (intaIsGvlPassThroughRequest(url)) {
            return open.apply(this, arguments);
        }
        let isExternal = !url.startsWith(window.location.origin);
        if (isExternal) {
            let consentType = getConsentTypeForUrl(url);
            if (!hasConsent(consentType)) {
                if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                    console.log('[GDPR] Blocked XHR:', url, 'type:', consentType);
                }
                // Silently block: do not send request
                return; // open not called, so request never sent
            }
        }
        return open.apply(this, arguments);
    };
    return xhr;
}
window.XMLHttpRequest = CustomXHR;
// Intercept navigator.sendBeacon with consent check
let originalSendBeacon = navigator.sendBeacon;
navigator.sendBeacon = function (url, data) {
    // Prevent recursion for backend endpoint
    if (isAllowed(url)) {
        return originalSendBeacon.apply(this, arguments);
    }
    if (intaIsGvlPassThroughRequest(url)) {
        return originalSendBeacon.apply(this, arguments);
    }
    let isExternal = !url.startsWith(window.location.origin);
    if (isExternal) {
        let consentType = getConsentTypeForUrl(url);
        if (!hasConsent(consentType)) {
            if (typeof intastellarDevMode !== 'undefined' && intastellarDevMode) {
                console.log('[GDPR] Blocked beacon:', url, 'type:', consentType);
            }
            // Silently block: do not send beacon
            return false;
        }
        sendToBackend({
            type: 'beacon',
            url,
            data: typeof data === 'string' ? data : '[binary]',
            consentType,
            timestamp: Date.now()
        });
    }
    return originalSendBeacon.apply(this, arguments);
};
// --- End Server-Side Tagging & Interception Implementtion ---


if (!hasConsent("advertisement")) {
    fbq('consent', 'revoke');
}

let settingsMessage = "";
let foundScripts = window.foundScripts = [];
let intCookieIcon = intastellarAssetsCDNdomain + "/assets/icons/cookie_settings.svg";
window.dataLayer = window.dataLayer || [];
(adsbygoogle = window.adsbygoogle || []).pauseAdRequests = 1;
(adsbygoogle = window.adsbygoogle || []).requestNonPersonalizedAds = 1;

/* - - - Setup - - - */
if (window.INTA === undefined) {
    window.INTA = {
        policy_link: undefined,
        settings: {
            company: undefined,
            lang: "auto",
            color: "#c09f53",
            keepInLocalStorage: ["firstLoad", int_FunctionalCookies, int_hideCookieBannerName, int_marketingCookies, int_staticsticCookies],
            arrange: "ltr",
            logo: intCookieIcon,
            partnerDomain: null,
            StyleSheet: null,
            design: "overlay",
        }
    }
}

function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(";");
    for (var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) === " ") {
            c = c.substring(1);
        }

        /* console.log(localStorage.getItem(cname), cname); */

        if (c.indexOf(name) === 0 && localStorage.getItem(cname) === null) {
            return c.substring(name.length, c.length);
        } else if (localStorage.getItem(cname) !== null) {
            return localStorage.getItem(cname);
        }
    }
    return "";
}

function randomIntFromInterval(min, max) { // min and max included 
    return Math.floor(Math.random() * (max - min + 1) + min)
}

/**
 * CCPA / CPRA: persist `salesOfDataAllowed` only for visitors in California (no extra banner checkbox).
 * Region: `window._intaGeo` from ipapi (see fetch above), or override `INTA.settings.ccpa.inUsCalifornia` (boolean),
 * or both `INTA.settings.ccpa.country === "US"` and `INTA.settings.ccpa.regionCode === "CA"` (e.g. server-injected).
 * Value: false if `localStorage.ccpa_opt_out` ("Do not sell" flow); else mirrors marketing consent (`advertisementCookies === "checked"`).
 * When region is still unknown, the field is left unchanged (not added, not removed) until geo or override is available.
 */
function intaCaliforniaRegionState() {
    try {
        var ccpa = window.INTA && window.INTA.settings && window.INTA.settings.ccpa;
        if (ccpa && typeof ccpa.inUsCalifornia === "boolean") {
            return ccpa.inUsCalifornia ? "yes" : "no";
        }
        if (ccpa && ccpa.country && ccpa.regionCode) {
            return (ccpa.country === "US" && ccpa.regionCode === "CA") ? "yes" : "no";
        }
        var g = window._intaGeo;
        if (g && g.country && g.region_code) {
            return (g.country === "US" && g.region_code === "CA") ? "yes" : "no";
        }
    } catch (e) { /* ignore */ }
    return "unknown";
}

function intaMarketingConsentImpliesSaleAllowed(consents) {
    if (!consents || typeof consents !== "object") return false;
    return consents.advertisementCookies === "checked" || consents.advertisementCookies === true;
}

function intaSyncSalesOfDataAllowedOnConsents(consents) {
    if (!consents || typeof consents !== "object") return;
    var region = intaCaliforniaRegionState();
    if (region === "no") {
        delete consents.salesOfDataAllowed;
        return;
    }
    if (region === "unknown") {
        return;
    }
    try {
        if (typeof localStorage !== "undefined" && localStorage.getItem("ccpa_opt_out") === "true") {
            consents.salesOfDataAllowed = false;
            return;
        }
    } catch (e) { /* ignore */ }
    consents.salesOfDataAllowed = intaMarketingConsentImpliesSaleAllowed(consents);
}

function encodeIntaConsentsObject(string, base) {
    try {
        var parsed = JSON.parse(string);
        if (parsed && typeof parsed === "object" && parsed.consents && typeof parsed.consents === "object") {
            intaSyncSalesOfDataAllowedOnConsents(parsed.consents);
            string = JSON.stringify(parsed);
        }
    } catch (e) {
        /* not a full consent JSON payload — encode as-is */
    }
    var number = "0";
    var length = string.length;
    for (var i = 0; i < length; i++)
        number += string.charCodeAt(i).toString(base);
    return base + "." + number;
}

function decodeIntaConsentsObject(number) {
    var string = "";
    number = number?.slice(1);
    var length = number?.length;
    for (var i = 0; i < length;) {
        var code = number?.slice(i, i += 2);
        string += String.fromCharCode(parseInt(code, parseInt(getCookie(int_hideCookieBannerName)?.split(".")[1])));
    }

    return string;
}

let intastellarDevMode = (function () {
    var hostname = window.location.hostname;
    return hostname === "localhost"
        || hostname.indexOf("127.0.0.1") > -1 && window.INTA.dev === true
        || hostname.indexOf("0.0.0.0") > -1 && window.INTA.dev === true
        || hostname.indexOf("192.168.") > -1 && window.INTA.dev === true
        || hostname.indexOf("::1") > -1 && window.INTA.dev === true
        ? true : false;
})();

let tmpl = document.createElement('template');
tmpl.innerHTML = `
<style>:host { display:block; width: auto; max-width: 560px; }</style> <!-- look ma, scoped styles -->
<slot></slot>
`;

/* - - - Function to get Cookie Settings from url and set the cookie - - - */
function intaSetCookieSettings() {
    let urlParams = new URLSearchParams(window.location.search);
    let cookieSettings = urlParams.get('intaCookieSettings');
    let reload = urlParams.get('reload');

    /*  console.log("Cookie Settings from URL", window.location.host); */
    if (cookieSettings && !reload) {
        /* console.log("Setting the new cookie" + cookieSettings); */

        document.cookie = int_hideCookieBannerName + "=" + cookieSettings + "; expires=" + cookieLifeTime +
            "; path=/; " +
            intCookieDomain +
            "SameSite=Lax";
        // Reload the page and append to exising query string the reload parameter
        window.location.href = window.location.href + "&reload=true";
    }
};
function processExistingScripts() {
    // Process blocked scripts that should now be allowed
    document.querySelectorAll('script[type="text/blocked"]').forEach(script => {
        let src = script.src || '';
        if (!notRequired.test(src) && !notRequired.test(script.innerText)) {
            // This script should now be allowed - replace it
            let newScript = document.createElement('script');
            newScript.type = 'text/javascript';
            if (script.src) newScript.src = script.src;
            if (script.innerText) newScript.text = script.innerText;
            script.parentNode?.replaceChild(newScript, script);
        }
    });

    // Process blocked iframes that should now be allowed
    document.querySelectorAll('inta-consents-iframe[data-src], inta-consents[data-src]').forEach(blocked => {
        let type = blocked.querySelector('.--changePermission')?.dataset?.type;
        if ((type === 'intMarketingCookies' && intaCookieConsents?.advertisementCookies === "checked") ||
            (type === 'intFunctionalCookies' && intaCookieConsents?.functionalCookies === "checked") ||
            (type === 'intStaticsCookies' && intaCookieConsents?.staticsticCookies === "checked")) {

            let iframe = document.createElement('iframe');
            iframe.src = blocked.getAttribute('data-src');
            iframe.border = '0';
            iframe.frameBorder = '0';

            if (blocked.getAttribute('data-class')) {
                iframe.setAttribute('class', blocked.getAttribute('data-class'));
            } else {
                iframe.width = '560';
                iframe.height = '315';
            }

            blocked.parentElement?.replaceChild(iframe, blocked);
        }
    });
}


function restartObserver() {
    // Disconnect any existing observer
    if (window.currentObserver) {
        window.currentObserver.disconnect();
    }

    // Create a new observer with updated consent settings
    window.currentObserver = checkCookieStatus();

    // Process any existing blocked content that should now be allowed
    processExistingScripts();

}

let beforeScriptExecuteListener = function (event, node) {
    let src = node.src || "";

    if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
        || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
        || !FunctionalCheckbox?.checked || !StaticsCheckBox?.checked || !MarketingCheckBox?.checked
    ) {
        if (
            src.indexOf(window.location.hostname) == -1
            && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
        ) {
            if (
                notRequired.test(src)
            ) {
                node.defer = true;
                node.async = true;
                node.type = "text/blocked";
                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
            }
        } else if (src.indexOf(window.location.hostname) == -1
            && src.indexOf("jquery") > -1) {
            node.type = "text/javascript";
            node.defer = false;
            node.async = false;
        } else {
            node.type = "text/javascript";
            /* if(document.querySelector(scriptTag) === null){
                node.parentElement.appendChild(scriptTag);
            } */
        }

        if (
            notRequired.test(node.innerText)
            && node.innerText.toLowerCase().indexOf("elementor") == -1
        ) {
            node.defer = true;
            node.async = true;
            node.type = "text/blocked";
            /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
        } else {
            /* if(document.querySelector(scriptTag) === null){
                node.parentElement.appendChild(scriptTag);
            } */
        }
    } else if (intaCookieConsents?.functionalCookies === "checked" &&
        intaCookieConsents?.advertisementCookies === "checked" &&
        intaCookieConsents?.staticsticCookies === "checked"
        || FunctionalCheckbox?.checked && StaticsCheckBox?.checked && MarketingCheckBox?.checked) {
        node.type = "text/javascript";
    }

    if (node.getAttribute("type") === "text/blocked")
        event.preventDefault();
    node.removeEventListener(
        "beforescriptexecute",
        (e, node) => beforeScriptExecuteListener(e, node)
    );

    // Disconnect the observer if it exists
    if (window.currentObserver) {
        window.currentObserver.disconnect();
    }
};

function checkCookieStatus() {
    if (isGtmMode) {
        /* console.log("Observer disabled in GTM mode"); */
        return null; // Return null instead of creating an observer
    }
    /* To get anonymous cookie banner usage */
    /* - - - Observer - - - */

    let __intaObserverPendingMutations = [];
    let __intaObserverDebounceTimer = null;
    let observer = new MutationObserver((mutations) => {
        for (let mi = 0; mi < mutations.length; mi++) {
            __intaObserverPendingMutations.push(mutations[mi]);
        }
        if (__intaObserverDebounceTimer !== null) {
            clearTimeout(__intaObserverDebounceTimer);
        }
        __intaObserverDebounceTimer = setTimeout(function () {
            __intaObserverDebounceTimer = null;
            let batch = __intaObserverPendingMutations;
            __intaObserverPendingMutations = [];
            requestAnimationFrame(() => {
                batch.forEach(({ addedNodes }) => {
                addedNodes.forEach((node) => {

                    if (node.nodeType === 1 && node.tagName === "DIV" || node.nodeType === 1 && node.tagName === "IFRAME") {
                        allScripts.map((script) => {
                            intaEnsureBlockedIframeMessagesLoaded();
                            let INTAlogo = (window.INT) ? window.INT.settings.logo : (window.INTA?.settings?.logo) ? window.INTA?.settings?.logo : null;
                            loopBlock(addedNodes, script, INTAlogo);
                        })
                    }

                    if (node.nodeType === 1 && node.tagName === "BLOCKQUOTE") {
                        allScripts.map((script) => {
                            addedNodes.forEach((tweet) => {
                                intaEnsureBlockedIframeMessagesLoaded();
                                let INTAlogo = (window.INT) ? window.INT.settings.logo : (window.INTA?.settings?.logo) ? window.INTA?.settings?.logo : null;
                                blockBlockQuotes(tweet, script, INTAlogo);
                            });
                        });
                    }

                    if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                        || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == "") {
                        if (node.nodeType === 1 && node.tagName === "LINK") {
                            addedNodes.forEach((link) => {
                                let linkSrc = link.href;
                                if (notRequired.test(linkSrc)) {
                                    link.disabled = true;
                                }
                            })
                        }
                    }

                    if (node.nodeType === 1 && node.tagName === "SCRIPT" && node.type !== 'application/ld+json' && node.innerText.indexOf("window.INTA") == -1 && node.innerText.indexOf("window.INT") == -1 && node.innerText.indexOf("window.INTA") == -1 && node.innerText.toLowerCase().indexOf("elementor") == -1 && node.innerText.toLowerCase().indexOf("chic_lite_data") == -1 && node.innerText.toLowerCase().indexOf("mailchimp_public_data") == -1 && node.innerText.toLowerCase().indexOf("monsterinsights_frontend") == -1) {
                        let src = node.src || "";


                        node.removeAttribute("charset");
                        addedNodes.forEach((node) => {

                            src = node.src;
                            if (src.indexOf(window.location.hostname) == -1) {
                                if (src.trim() === "") {
                                    return;
                                }
                                window.foundScripts.push(src);
                                // Filter out scripts that are empty or contain only whitespace

                            }

                            if (intaCookieConsents?.advertisementCookies === "checked" || intaCookieConsents?.functionalCookies === "checked" || intaCookieConsents?.staticsticCookies === "checked"
                                || FunctionalCheckbox?.checked || StaticsCheckBox?.checked || MarketingCheckBox?.checked
                            ) {
                                node.type = "text/javascript";
                                return;
                            }



                            if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                                || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
                                || !FunctionalCheckbox?.checked && !StaticsCheckBox?.checked && !MarketingCheckBox?.checked
                            ) {
                                if (
                                    src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
                                ) {
                                    if (
                                        notRequired.test(src)
                                    ) {
                                        node.type = "text/blocked";
                                        node.defer = true;
                                        node.async = true;

                                        /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/

                                        /* deleteAllCookies(); */
                                    }
                                } else if (src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == 1) {
                                    node.type = "text/javascript";
                                    node.defer = false;
                                    node.async = false;
                                }

                                if (
                                    notRequired.test(node.innerText)
                                ) {
                                    node.defer = true;
                                    node.async = true;
                                    node.type = "text/blocked";
                                    /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                    /* deleteAllCookies(); */
                                }
                            } else if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1
                                || intaCookieConsents?.advertisementCookies == "false" &&
                                getCookie(int_hideCookieBannerName) != "" &&
                                getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 &&
                                intaCookieConsents?.functionalCookies == "false" &&
                                getCookie(int_hideCookieBannerName) != "" &&
                                getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 &&
                                intaCookieConsents?.staticsticCookies == "false" ||
                                intaCookieConsents?.advertisementCookies == "null" &&
                                intaCookieConsents?.functionalCookies == "null" &&
                                intaCookieConsents?.staticsticCookies == "null"
                                || intaCookieConsents?.advertisementCookies == "" &&
                                intaCookieConsents?.functionalCookies == "" &&
                                intaCookieConsents?.staticsticCookies == ""
                                || !FunctionalCheckbox?.checked &&
                                !StaticsCheckBox?.checked &&
                                !MarketingCheckBox?.checked
                            ) {
                                if (
                                    src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == -1 && src.indexOf("elementor") == -1
                                ) {
                                    if (
                                        notRequired.test(src)
                                    ) {
                                        node.type = "text/blocked";
                                        node.defer = true;
                                        node.async = true;
                                        /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                    }
                                } else if (src.indexOf(window.location.hostname) == -1
                                    && src.indexOf("jquery") == 1) {
                                    node.type = "text/javascript";
                                    node.defer = false;
                                    node.async = false;
                                }
                                if (
                                    notRequired.test(node.innerText)
                                    && node.innerText.toLowerCase().indexOf("elementor") == -1
                                ) {
                                    node.type = "text/blocked";
                                    node.defer = true;
                                    node.async = true;
                                    /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                }
                            }

                            if (node.getAttribute("type") === "text/blocked") {
                                node.addEventListener(
                                    "beforescriptexecute",
                                    (e) => beforeScriptExecuteListener(e, node)
                                );
                            }
                        });
                    } else if (node.nodeType === 1 && node.tagName === "NOSCRIPT" && node.type !== 'application/ld+json' && node.innerText.indexOf("window.INTA") == -1 && node.innerText.indexOf("window.INT") == -1 && node.innerText.toLowerCase().indexOf("elementor") == -1) {
                        if (getCookie(int_hideCookieBannerName) == "" || getCookie(int_hideCookieBannerName)?.indexOf("__inta") == -1 || intaCookieConsents?.advertisementCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.functionalCookies == "false" && getCookie(int_hideCookieBannerName) != "" && getCookie(int_hideCookieBannerName)?.indexOf("__inta") > -1 && intaCookieConsents?.staticsticCookies == "false" || intaCookieConsents?.advertisementCookies == "null" && intaCookieConsents?.functionalCookies == "null" && intaCookieConsents?.staticsticCookies == "null"
                            || intaCookieConsents?.advertisementCookies == "" && intaCookieConsents?.functionalCookies == "" && intaCookieConsents?.staticsticCookies == ""
                            || FunctionalCheckbox?.checked && StaticsCheckBox?.checked && MarketingCheckBox?.checked
                        ) {

                            if (
                                notRequired.test(node.innerText)
                                && node.innerText.toLowerCase().indexOf("elementor") == -1
                            ) {
                                node.defer = true;
                                node.async = true;
                                node.type = "text/blocked";
                                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                                /* deleteAllCookies(); */
                            }
                        } else if (intaCookieConsents?.functionalCookies == "false" && intaCookieConsents?.advertisementCookies == "false" && intaCookieConsents?.staticsticCookies == "false"
                            || !FunctionalCheckbox?.checked && !StaticsCheckBox?.checked && !MarketingCheckBox?.checked
                        ) {

                            if (
                                notRequired.test(node.innerText)
                                && node.innerText.toLowerCase().indexOf("elementor") == -1
                            ) {
                                node.defer = true;
                                node.async = true;
                                node.type = "text/blocked";
                                /*if(node.parentElement !== null) node.parentElement.removeChild(node);*/
                            } else {
                                /* node.parentElement.appendChild(node); */
                            }
                        } else if (intaCookieConsents?.functionalCookies === "checked" &&
                            intaCookieConsents?.advertisementCookies === "checked" &&
                            intaCookieConsents?.staticsticCookies === "checked" ||
                            FunctionalCheckbox?.checked &&
                            StaticsCheckBox?.checked &&
                            MarketingCheckBox?.checked

                        ) {
                            node.type = "text/javascript";
                        }
                    }
                });
            });
        });
        }, 80);
    });
    startObserving(observer, document.documentElement);
    return observer;

}

function startObserving(observer) {
    observer.observe(document.documentElement, {
        childList: !0,
        subtree: !0,
        attributes: true,
        attributeFilter: ["src", "href", "type", "value", "checked", "innerText"],
    })
}

window.inta_marketingCookieList = window.inta_marketingCookieList || [];
window.inta_functionalCookieList = window.inta_functionalCookieList || [];

function sendToBackend(data) {
    if (typeof window.__intaSendToBackendImpl === "function") {
        return window.__intaSendToBackendImpl(data);
    }
    return Promise.resolve();
}

function recordCookie(value) {
    window.__INTA__COOKIE_EVENTS__ = window.__INTA__COOKIE_EVENTS__ || [];
    window.__INTA__COOKIE_EVENTS__.push(value);
    if (typeof window.__intaRecordCookieImpl === "function") {
        return window.__intaRecordCookieImpl(value);
    }
    window.__intaPendingCookieRecords = window.__intaPendingCookieRecords || [];
    window.__intaPendingCookieRecords.push(value);
}

function intaLoadUcCore() {
    if (window.__intaUcCoreReady || window.__intaUcCoreLoading) {
        return;
    }
    window.__intaUcCoreLoading = true;
    var base = (typeof window.INTA !== "undefined" && window.INTA.settings && window.INTA.settings.coreUrl)
        || "https://consents.cdn.intastellarsolutions.com/uc-core.js";
    if (typeof intastellarDevMode !== "undefined" && intastellarDevMode) {
        base = "../../dev/uc-core.dev.js";
    }
    try {
        var preload = document.createElement("link");
        preload.rel = "preload";
        preload.as = "script";
        preload.href = base;
        preload.crossOrigin = "anonymous";
        (document.head || document.documentElement).appendChild(preload);
    } catch (ePre) { /* ignore */ }
    var s = document.createElement("script");
    s.src = base;
    s.async = true;
    s.onload = function () {
        window.__intaUcCoreReady = true;
        window.__intaUcCoreLoading = false;
        try {
            window.dispatchEvent(new CustomEvent("inta:uc-core-ready"));
        } catch (e) { /* ignore */ }
    };
    s.onerror = function () {
        window.__intaUcCoreLoading = false;
    };
    if (typeof intaAppendToDocumentHead === "function") {
        intaAppendToDocumentHead(s);
    } else {
        (document.head || document.documentElement).appendChild(s);
    }
}

if (!isGtmMode) {
    checkCookieStatus();
}

intaLoadUcCore();
